#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 3 "..\..\Views\Shared\_Footer.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cutecms_porto;
    
    #line 2 "..\..\Views\Shared\_Footer.cshtml"
    using cutecms_porto.Areas.CMS.Models.DBModel;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Shared\_Footer.cshtml"
    using cutecms_porto.Areas.Config.Models.DBModel;
    
    #line default
    #line hidden
    using cutecms_porto.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Footer.cshtml")]
    public partial class _Views_Shared__Footer_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Footer_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\_Footer.cshtml"
  
    CMSEntities db = new CMSEntities();
    var organizations = (List<Organization>)HttpRuntime.Cache["Organizations"];
    var organization = organizations.Where(o => o.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name)).FirstOrDefault();
    IEnumerable<MenuItem> footerMenuItems = db.MenuItems.Include("Status").Include("Menu").Include("Language").Where(m => m.Menu.TenantId.Trim().Equals(Tenant.TenantId) && m.Menu.Code.Trim().Equals("footer-menu") && m.Status.Code.Trim().Equals("published") && m.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name)).OrderBy(o => o.Ordinal);

            
            #line default
            #line hidden
WriteLiteral("\r\n<footer");

WriteLiteral(" id=\"footer\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"footer-ribbon\"");

WriteLiteral(">\r\n                <span>");

            
            #line 14 "..\..\Views\Shared\_Footer.cshtml"
                 Write(Resources.Resources.KeepInTouch);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"newsletter\"");

WriteLiteral(">\r\n                    <h4>");

            
            #line 18 "..\..\Views\Shared\_Footer.cshtml"
                   Write(Resources.Resources.Newsletter);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                    <p>");

            
            #line 19 "..\..\Views\Shared\_Footer.cshtml"
                  Write(Resources.Resources.SubscriptionMessage);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n                    ");

WriteLiteral("\r\n");

            
            #line 26 "..\..\Views\Shared\_Footer.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\_Footer.cshtml"
                      
                        cutecms_porto.Models.SubscriberViewModel subscriber = new cutecms_porto.Models.SubscriberViewModel();
                    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 29 "..\..\Views\Shared\_Footer.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Shared\_Footer.cshtml"
                      Html.RenderPartial("~/Views/Shared/Subscribe.cshtml", subscriber);
            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                <h4>");

            
            #line 33 "..\..\Views\Shared\_Footer.cshtml"
               Write(Resources.Resources.LatestTweets);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                <div");

WriteLiteral(" id=\"tweet\"");

WriteLiteral(" class=\"twitter\"");

WriteLiteral(" data-plugin-tweets");

WriteLiteral(" data-plugin-options=\'{\"username\": \"\", \"count\": 2}\'");

WriteLiteral(">\r\n                    <p>");

            
            #line 35 "..\..\Views\Shared\_Footer.cshtml"
                  Write(Resources.Resources.PleaseWait);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"contact-details\"");

WriteLiteral(">\r\n                    <h4>");

            
            #line 40 "..\..\Views\Shared\_Footer.cshtml"
                   Write(Resources.Resources.ContactUs);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                    <ul");

WriteLiteral(" class=\"contact\"");

WriteLiteral(">\r\n                        <li><p><i");

WriteLiteral(" class=\"fa fa-map-marker\"");

WriteLiteral("></i> <strong>");

            
            #line 42 "..\..\Views\Shared\_Footer.cshtml"
                                                                   Write(Resources.Resources.Address);

            
            #line default
            #line hidden
WriteLiteral(":</strong> ");

            
            #line 42 "..\..\Views\Shared\_Footer.cshtml"
                                                                                                          Write(organization.AddressLine1);

            
            #line default
            #line hidden
WriteLiteral(", ");

            
            #line 42 "..\..\Views\Shared\_Footer.cshtml"
                                                                                                                                      Write(organization.City);

            
            #line default
            #line hidden
WriteLiteral(", ");

            
            #line 42 "..\..\Views\Shared\_Footer.cshtml"
                                                                                                                                                          Write(organization.Country);

            
            #line default
            #line hidden
WriteLiteral("</p></li>\r\n                        <li><p><i");

WriteLiteral(" class=\"fa fa-phone\"");

WriteLiteral("></i> <strong>");

            
            #line 43 "..\..\Views\Shared\_Footer.cshtml"
                                                              Write(Resources.Resources.Phone);

            
            #line default
            #line hidden
WriteLiteral(":</strong> ");

            
            #line 43 "..\..\Views\Shared\_Footer.cshtml"
                                                                                                   Write(organization.Telephone);

            
            #line default
            #line hidden
WriteLiteral("</p></li>\r\n                        <li><p><i");

WriteLiteral(" class=\"fa fa-envelope\"");

WriteLiteral("></i> <strong>");

            
            #line 44 "..\..\Views\Shared\_Footer.cshtml"
                                                                 Write(Resources.Resources.Email);

            
            #line default
            #line hidden
WriteLiteral(":</strong> <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2725), Tuple.Create("\"", 2758)
, Tuple.Create(Tuple.Create("", 2732), Tuple.Create("mailto:", 2732), true)
            
            #line 44 "..\..\Views\Shared\_Footer.cshtml"
                                           , Tuple.Create(Tuple.Create("", 2739), Tuple.Create<System.Object, System.Int32>(organization.Email
            
            #line default
            #line hidden
, 2739), false)
);

WriteLiteral(">");

            
            #line 44 "..\..\Views\Shared\_Footer.cshtml"
                                                                                                                                           Write(organization.Email);

            
            #line default
            #line hidden
WriteLiteral("</a></p></li>\r\n                    </ul>\r\n                </div>\r\n            </d" +
"iv>\r\n            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                <h4>");

            
            #line 49 "..\..\Views\Shared\_Footer.cshtml"
               Write(Resources.Resources.FollowUs);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                <ul");

WriteLiteral(" class=\"social-icons\"");

WriteLiteral(">\r\n");

            
            #line 51 "..\..\Views\Shared\_Footer.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Shared\_Footer.cshtml"
                     foreach (var item in organization.SocialNetworks)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li");

WriteAttribute("class", Tuple.Create(" class=\"", 3122), Tuple.Create("\"", 3153)
, Tuple.Create(Tuple.Create("", 3130), Tuple.Create("social-icons-", 3130), true)
            
            #line 53 "..\..\Views\Shared\_Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3143), Tuple.Create<System.Object, System.Int32>(item.Code
            
            #line default
            #line hidden
, 3143), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3157), Tuple.Create("\"", 3173)
            
            #line 53 "..\..\Views\Shared\_Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3164), Tuple.Create<System.Object, System.Int32>(item.Url
            
            #line default
            #line hidden
, 3164), false)
);

WriteLiteral(" target=\"_blank\"");

WriteAttribute("title", Tuple.Create(" title=\"", 3190), Tuple.Create("\"", 3208)
            
            #line 53 "..\..\Views\Shared\_Footer.cshtml"
                       , Tuple.Create(Tuple.Create("", 3198), Tuple.Create<System.Object, System.Int32>(item.Name
            
            #line default
            #line hidden
, 3198), false)
);

WriteLiteral("><i");

WriteAttribute("class", Tuple.Create(" class=\"", 3212), Tuple.Create("\"", 3237)
, Tuple.Create(Tuple.Create("", 3220), Tuple.Create("fa", 3220), true)
            
            #line 53 "..\..\Views\Shared\_Footer.cshtml"
                                               , Tuple.Create(Tuple.Create(" ", 3222), Tuple.Create<System.Object, System.Int32>(item.CssClass
            
            #line default
            #line hidden
, 3223), false)
);

WriteLiteral("></i></a></li>\r\n");

            
            #line 54 "..\..\Views\Shared\_Footer.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </ul>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"footer-copyright\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-1\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3510), Tuple.Create("\"", 3542)
, Tuple.Create(Tuple.Create("", 3517), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/index.html")
, 3517), false)
);

WriteLiteral(" class=\"logo\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" alt=\"CuteCMS.NET\"");

WriteLiteral(" class=\"img-responsive\"");

WriteAttribute("src", Tuple.Create(" src=\"", 3628), Tuple.Create("\"", 3668)
, Tuple.Create(Tuple.Create("", 3634), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/img/footer-logo.png")
, 3634), false)
);

WriteLiteral(">\r\n                    </a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-md-7\"");

WriteLiteral(">\r\n                    <p>© ");

            
            #line 68 "..\..\Views\Shared\_Footer.cshtml"
                    Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 68 "..\..\Views\Shared\_Footer.cshtml"
                                       Write(organization.Name);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 68 "..\..\Views\Shared\_Footer.cshtml"
                                                            Write(Resources.Resources.CopyRights);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                    <nav");

WriteLiteral(" id=\"sub-menu\"");

WriteLiteral(">\r\n                        <ul>\r\n");

            
            #line 73 "..\..\Views\Shared\_Footer.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 73 "..\..\Views\Shared\_Footer.cshtml"
                             foreach (var item in footerMenuItems)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 4136), Tuple.Create("\"", 4153)
            
            #line 75 "..\..\Views\Shared\_Footer.cshtml"
, Tuple.Create(Tuple.Create("", 4143), Tuple.Create<System.Object, System.Int32>(item.Path
            
            #line default
            #line hidden
, 4143), false)
);

WriteLiteral(">");

            
            #line 75 "..\..\Views\Shared\_Footer.cshtml"
                                                    Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 76 "..\..\Views\Shared\_Footer.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral("\r\n                        </ul>\r\n                    </nav>\r\n                </di" +
"v>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</footer>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
