#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 3 "..\..\Views\Shared\_Layout.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 4 "..\..\Views\Shared\_Layout.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cutecms_porto;
    
    #line 1 "..\..\Views\Shared\_Layout.cshtml"
    using cutecms_porto.Areas.CMS.Models.DBModel;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\_Layout.cshtml"
    using cutecms_porto.Areas.Config.Models.DBModel;
    
    #line default
    #line hidden
    using cutecms_porto.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Shared\_Layout.cshtml"
  
    CMSEntities db = new CMSEntities();
    CultureInfo cultureInfo = Thread.CurrentThread.CurrentCulture;
    RegionInfo regionInfo = new RegionInfo(cultureInfo.LCID);
    var languages = db.CMSLanguages.Where(l => l.IsEnabled == true).OrderByDescending(l => l.IsDefault).ThenBy(l => l.Ordinal).ToList();
    var organizations = (List<Organization>)HttpRuntime.Cache["Organizations"];
    var organization = organizations.Where(o => o.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name))?.FirstOrDefault() ?? new Organization();

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteAttribute("dir", Tuple.Create(" dir=\"", 741), Tuple.Create("\"", 794)
            
            #line 14 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 747), Tuple.Create<System.Object, System.Int32>(CultureHelper.IsRighToLeft() ? "rtl" : "ltr"
            
            #line default
            #line hidden
, 747), false)
);

WriteLiteral(" class=\"boxed\"");

WriteLiteral(">\r\n<head>\r\n\r\n    <!-- Basic -->\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n\r\n    <title>");

            
            #line 21 "..\..\Views\Shared\_Layout.cshtml"
       Write(organization?.Name);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 21 "..\..\Views\Shared\_Layout.cshtml"
                              Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\r\n    <meta");

WriteLiteral(" name=\"keywords\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1017), Tuple.Create("\"", 1058)
            
            #line 23 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1027), Tuple.Create<System.Object, System.Int32>(organization.MetaDescription
            
            #line default
            #line hidden
, 1027), false)
);

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1092), Tuple.Create("\"", 1133)
            
            #line 24 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1102), Tuple.Create<System.Object, System.Int32>(organization.MetaDescription
            
            #line default
            #line hidden
, 1102), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"author\"");

WriteLiteral(" content=\"CuteCMS.NET\"");

WriteLiteral(">\r\n\r\n    <!-- Favicon -->\r\n    <link");

WriteLiteral(" rel=\"shortcut icon\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1238), Tuple.Create("\"", 1275)
, Tuple.Create(Tuple.Create("", 1245), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/img/favicon.ico")
, 1245), false)
);

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1333), Tuple.Create("\"", 1379)
, Tuple.Create(Tuple.Create("", 1340), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/img/apple-touch-icon.png")
, 1340), false)
);

WriteLiteral(">\r\n\r\n    <!-- Mobile Metas -->\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable" +
"=no\"");

WriteLiteral(">\r\n\r\n    <!-- Web Fonts  -->\r\n    <link async");

WriteLiteral(" href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CSh" +
"adows+Into+Light\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n\r\n    <!-- Vendor CSS -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1754), Tuple.Create("\"", 1814)
, Tuple.Create(Tuple.Create("", 1761), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/bootstrap/css/bootstrap.min.css")
, 1761), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1844), Tuple.Create("\"", 1910)
, Tuple.Create(Tuple.Create("", 1851), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/font-awesome/css/font-awesome.min.css")
, 1851), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1940), Tuple.Create("\"", 1992)
, Tuple.Create(Tuple.Create("", 1947), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/animate/animate.min.css")
, 1947), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2022), Tuple.Create("\"", 2098)
, Tuple.Create(Tuple.Create("", 2029), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/simple-line-icons/css/simple-line-icons.min.css")
, 2029), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2128), Tuple.Create("\"", 2197)
, Tuple.Create(Tuple.Create("", 2135), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/owl.carousel/assets/owl.carousel.min.css")
, 2135), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2227), Tuple.Create("\"", 2301)
, Tuple.Create(Tuple.Create("", 2234), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/owl.carousel/assets/owl.theme.default.min.css")
, 2234), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2331), Tuple.Create("\"", 2397)
, Tuple.Create(Tuple.Create("", 2338), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/magnific-popup/magnific-popup.min.css")
, 2338), false)
);

WriteLiteral(">\r\n");

            
            #line 45 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Shared\_Layout.cshtml"
     if (CultureHelper.IsRighToLeft())
    {


            
            #line default
            #line hidden
WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2480), Tuple.Create("\"", 2540)
, Tuple.Create(Tuple.Create("", 2487), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/bootstrap-rtl/bootstrap-rtl.css")
, 2487), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("        <!-- Theme CSS  -->\r\n");

WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2605), Tuple.Create("\"", 2644)
, Tuple.Create(Tuple.Create("", 2612), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/css/rtl-theme.css")
, 2612), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2678), Tuple.Create("\"", 2726)
, Tuple.Create(Tuple.Create("", 2685), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/css/rtl-theme-elements.css")
, 2685), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2760), Tuple.Create("\"", 2804)
, Tuple.Create(Tuple.Create("", 2767), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/css/rtl-theme-blog.css")
, 2767), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2838), Tuple.Create("\"", 2882)
, Tuple.Create(Tuple.Create("", 2845), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/css/rtl-theme-shop.css")
, 2845), false)
);

WriteLiteral(">\r\n");

            
            #line 54 "..\..\Views\Shared\_Layout.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2940), Tuple.Create("\"", 2975)
, Tuple.Create(Tuple.Create("", 2947), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/css/theme.css")
, 2947), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3009), Tuple.Create("\"", 3053)
, Tuple.Create(Tuple.Create("", 3016), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/css/theme-elements.css")
, 3016), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3087), Tuple.Create("\"", 3127)
, Tuple.Create(Tuple.Create("", 3094), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/css/theme-blog.css")
, 3094), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3161), Tuple.Create("\"", 3201)
, Tuple.Create(Tuple.Create("", 3168), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/css/theme-shop.css")
, 3168), false)
);

WriteLiteral(">\r\n");

            
            #line 61 "..\..\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <!-- Current Page CSS -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3269), Tuple.Create("\"", 3324)
, Tuple.Create(Tuple.Create("", 3276), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/rs-plugin/css/settings.css")
, 3276), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3354), Tuple.Create("\"", 3407)
, Tuple.Create(Tuple.Create("", 3361), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/rs-plugin/css/layers.css")
, 3361), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3437), Tuple.Create("\"", 3494)
, Tuple.Create(Tuple.Create("", 3444), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/rs-plugin/css/navigation.css")
, 3444), false)
);

WriteLiteral(">\r\n\r\n    <!-- Skin CSS -->\r\n   ");

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3626), Tuple.Create("\"", 3674)
, Tuple.Create(Tuple.Create("", 3633), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/css/skins/skin-medical.css")
, 3633), false)
);

WriteLiteral(">\r\n    <!-- Demo CSS -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3727), Tuple.Create("\"", 3775)
, Tuple.Create(Tuple.Create("", 3734), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/css/demos/demo-medical.css")
, 3734), false)
);

WriteLiteral(">\r\n\r\n    <!-- Theme Custom CSS -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3838), Tuple.Create("\"", 3874)
, Tuple.Create(Tuple.Create("", 3845), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/css/custom.css")
, 3845), false)
);

WriteLiteral(">\r\n\r\n    <!-- Head Libs -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3915), Tuple.Create("\"", 3969)
, Tuple.Create(Tuple.Create("", 3921), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/modernizr/modernizr.min.js")
, 3921), false)
);

WriteLiteral("></script>\r\n\r\n");

            
            #line 79 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\Shared\_Layout.cshtml"
     if (cutecms_porto.Helpers.CultureHelper.IsRighToLeft())
    {

            
            #line default
            #line hidden
WriteLiteral(@"        <style>
            .dropdown-menu .edge ul {
                left: 100% !important;
                right: auto !important;
            }

            #topNav div.submenu-dark ul.dropdown-menu a.dropdown-toggle {
                padding-left: 25px;
            }
            .team .thumb-info .thumb-info-caption .custom-thumb-info-title i {
                left: 20px !important;
            }

            .team .owl-carousel.nav-bottom .owl-nav {
                left: 10px !important;
            }
        </style>
");

            
            #line 98 "..\..\Views\Shared\_Layout.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral(@"        <style>
            .dropdown-menu .edge ul {
                left: auto !important;
                right: 100% !important;
                /*background: rgba(86, 86, 86, 1) !important;*/
            }

            #topNav div.submenu-dark ul.dropdown-menu a.dropdown-toggle {
                padding-right: 25px;
            }
            .team .thumb-info .thumb-info-caption .custom-thumb-info-title i {
                right: 20px !important;
            }

            .team .owl-carousel.nav-bottom .owl-nav {
                right: 10px !important;
            }
        </style>
");

            
            #line 119 "..\..\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 120 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5292), Tuple.Create("\"", 5340)
, Tuple.Create(Tuple.Create("", 5298), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/jquery/jquery.min.js")
, 5298), false)
);

WriteLiteral("></script>\r\n\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"body\"");

WriteLiteral(">\r\n        <header");

WriteLiteral(" id=\"header\"");

WriteLiteral(" class=\"header-mobile-nav-only\"");

WriteLiteral(" data-plugin-options=\'{\"stickyEnabled\": true, \"stickyEnableOnBoxed\": true, \"stick" +
"yEnableOnMobile\": true, \"stickyStartAt\": 52, \"stickySetTop\": \"-52px\", \"stickyCha" +
"ngeLogo\": true}\'");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"header-body\"");

WriteLiteral(" style=\"top:0px\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"header-top\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                        <nav");

WriteLiteral(" class=\"header-nav-top\"");

WriteLiteral(" style=\"margin-left:0px;\"");

WriteLiteral(">\r\n                            <ul");

WriteLiteral(" class=\"nav nav-pills\"");

WriteLiteral(">\r\n                                <li>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" id=\"dropdownLanguage\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 6131), Tuple.Create("\"", 6165)
, Tuple.Create(Tuple.Create("", 6137), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/img/blank.gif")
, 6137), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 6166), Tuple.Create("\"", 6228)
, Tuple.Create(Tuple.Create("", 6174), Tuple.Create("flag", 6174), true)
, Tuple.Create(Tuple.Create(" ", 6178), Tuple.Create("flag-", 6179), true)
            
            #line 134 "..\..\Views\Shared\_Layout.cshtml"
                 , Tuple.Create(Tuple.Create("", 6184), Tuple.Create<System.Object, System.Int32>(regionInfo.TwoLetterISORegionName.ToLower()
            
            #line default
            #line hidden
, 6184), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 6229), Tuple.Create("\"", 6258)
            
            #line 134 "..\..\Views\Shared\_Layout.cshtml"
                                                                    , Tuple.Create(Tuple.Create("", 6235), Tuple.Create<System.Object, System.Int32>(regionInfo.DisplayName
            
            #line default
            #line hidden
, 6235), false)
);

WriteLiteral("> ");

            
            #line 134 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                                                                         Write(regionInfo.NativeName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <i");

WriteLiteral(" class=\"fa fa-globe\"");

WriteLiteral("></i>\r\n                                    </a>\r\n                                " +
"    <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(" aria-labelledby=\"dropdownLanguage\"");

WriteLiteral(">\r\n");

            
            #line 138 "..\..\Views\Shared\_Layout.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 138 "..\..\Views\Shared\_Layout.cshtml"
                                         foreach (var item in languages)
                                        {
                                            CultureInfo itemCultureInfo = CultureInfo.CreateSpecificCulture(item.CultureName.Trim());
                                            RegionInfo itemRegionInfo = new RegionInfo(itemCultureInfo.LCID);

            
            #line default
            #line hidden
WriteLiteral("                                            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6908), Tuple.Create("\"", 7070)
            
            #line 142 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 6915), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(new RouteValueDictionary(ViewContext.RouteData.Values.ToDictionary(r => r.Key, r => r.Key == "culture" ? item.CultureName.Trim() : r.Value)))
            
            #line default
            #line hidden
, 6915), false)
);

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 7076), Tuple.Create("\"", 7110)
, Tuple.Create(Tuple.Create("", 7082), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/img/blank.gif")
, 7082), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 7111), Tuple.Create("\"", 7143)
, Tuple.Create(Tuple.Create("", 7119), Tuple.Create("flag", 7119), true)
, Tuple.Create(Tuple.Create(" ", 7123), Tuple.Create("flag-", 7124), true)
            
            #line 142 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                                                                                               , Tuple.Create(Tuple.Create("", 7129), Tuple.Create<System.Object, System.Int32>(item.FlagCode
            
            #line default
            #line hidden
, 7129), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 7144), Tuple.Create("\"", 7176)
            
            #line 142 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                                                                                                                    , Tuple.Create(Tuple.Create("", 7150), Tuple.Create<System.Object, System.Int32>(itemRegionInfo.NativeName
            
            #line default
            #line hidden
, 7150), false)
);

WriteLiteral("> ");

            
            #line 142 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                                                                                                                                                                                                                            Write(itemRegionInfo.NativeName);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 143 "..\..\Views\Shared\_Layout.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </ul>\r\n                                </li>\r" +
"\n                            </ul>\r\n                        </nav>\r\n");

            
            #line 148 "..\..\Views\Shared\_Layout.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 148 "..\..\Views\Shared\_Layout.cshtml"
                          Html.RenderAction("GetTopMenu", "Home", new { area = "" });
            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"header-search hidden-xs\"");

WriteLiteral(">\r\n");

            
            #line 150 "..\..\Views\Shared\_Layout.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 150 "..\..\Views\Shared\_Layout.cshtml"
                             using (Html.BeginForm("Contents", "Home", new { area = "" }, FormMethod.Post))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 153 "..\..\Views\Shared\_Layout.cshtml"
                               Write(Html.Editor("keywordFilter", new { htmlAttributes = new { @placeholder = Resources.Resources.Search, @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                                        <button");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i></button>\r\n                                    </span>\r\n                    " +
"            </div>\r\n");

            
            #line 158 "..\..\Views\Shared\_Layout.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n\r\n                    </div>\r\n                </d" +
"iv>\r\n                <div");

WriteLiteral(" class=\"header-container container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"header-row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"header-column\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"header-logo\"");

WriteLiteral(">\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 8567), Tuple.Create("\"", 8617)
, Tuple.Create(Tuple.Create("", 8574), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 8574), false)
            
            #line 167 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 8576), Tuple.Create<System.Object, System.Int32>(Thread.CurrentThread.CurrentCulture.Name
            
            #line default
            #line hidden
, 8576), false)
);

WriteLiteral(">\r\n                                    <img");

WriteAttribute("alt", Tuple.Create(" alt=\"", 8661), Tuple.Create("\"", 8699)
            
            #line 168 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 8667), Tuple.Create<System.Object, System.Int32>(organization?.PrimaryLogoName
            
            #line default
            #line hidden
, 8667), false)
);

WriteLiteral(" width=\"110\"");

WriteLiteral(" height=\"110\"");

WriteLiteral(" data-sticky-width=\"90\"");

WriteLiteral(" data-sticky-height=\"90\"");

WriteLiteral(" data-sticky-top=\"15\"");

WriteAttribute("src", Tuple.Create(" src=\"", 8793), Tuple.Create("\"", 8831)
            
            #line 168 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                   , Tuple.Create(Tuple.Create("", 8799), Tuple.Create<System.Object, System.Int32>(organization?.PrimaryLogoPath
            
            #line default
            #line hidden
, 8799), false)
);

WriteLiteral(" style=\"top: 0; width: 110px; height: 100px;\"");

WriteLiteral(">\r\n                                    ");

WriteLiteral("\r\n                                </a>\r\n                            </div>\r\n     " +
"                   </div>\r\n                        <div");

WriteLiteral(" class=\"header-column\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"header-row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"header-nav header-nav-stripe\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" class=\"btn header-btn-collapse-nav\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".header-nav-main\"");

WriteLiteral(">\r\n                                        <i");

WriteLiteral(" class=\"fa fa-bars\"");

WriteLiteral("></i>\r\n                                    </button>\r\n                           " +
"         <div");

WriteLiteral(" class=\"header-nav-main header-nav-main-square header-nav-main-effect-1 header-na" +
"v-main-sub-effect-1 collapse\"");

WriteLiteral(">\r\n                                        <nav>\r\n                               " +
"             <ul");

WriteLiteral(" class=\"nav nav-pills\"");

WriteLiteral(" id=\"mainNav\"");

WriteLiteral(">\r\n                                                <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">\r\n                                                    <a");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteAttribute("href", Tuple.Create(" href=\"", 10094), Tuple.Create("\"", 10144)
, Tuple.Create(Tuple.Create("", 10101), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 10101), false)
            
            #line 183 "..\..\Views\Shared\_Layout.cshtml"
      , Tuple.Create(Tuple.Create("", 10103), Tuple.Create<System.Object, System.Int32>(Thread.CurrentThread.CurrentCulture.Name
            
            #line default
            #line hidden
, 10103), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                                                        ");

            
            #line 184 "..\..\Views\Shared\_Layout.cshtml"
                                                   Write(Resources.Resources.Home);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                    </a>\r\n                     " +
"                           </li>\r\n");

            
            #line 187 "..\..\Views\Shared\_Layout.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 187 "..\..\Views\Shared\_Layout.cshtml"
                                                  Html.RenderAction("GetHeaderMenu", "Home", new { area = "" });
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 188 "..\..\Views\Shared\_Layout.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 188 "..\..\Views\Shared\_Layout.cshtml"
                                                  Html.RenderPartial("~/Views/Shared/Account.cshtml");
            
            #line default
            #line hidden
WriteLiteral(@"
                                            </ul>
                                        </nav>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
");

WriteLiteral("            ");

            
            #line 198 "..\..\Views\Shared\_Layout.cshtml"
       Write(Html.Partial("_NewsBar"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </header>\r\n");

WriteLiteral("        ");

            
            #line 200 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderSection("PageHeader", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" role=\"main\"");

WriteLiteral(" class=\"main\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 202 "..\..\Views\Shared\_Layout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 204 "..\..\Views\Shared\_Layout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 204 "..\..\Views\Shared\_Layout.cshtml"
          Html.RenderAction("GetFooter", "Home", new { area = "" });
            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <!-- Vendor -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11188), Tuple.Create("\"", 11250)
, Tuple.Create(Tuple.Create("", 11194), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/jquery.appear/jquery.appear.min.js")
, 11194), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11274), Tuple.Create("\"", 11336)
, Tuple.Create(Tuple.Create("", 11280), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/jquery.easing/jquery.easing.min.js")
, 11280), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11360), Tuple.Create("\"", 11422)
, Tuple.Create(Tuple.Create("", 11366), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/jquery-cookie/jquery-cookie.min.js")
, 11366), false)
);

WriteLiteral("></script>\r\n    ");

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11534), Tuple.Create("\"", 11591)
, Tuple.Create(Tuple.Create("", 11540), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/bootstrap/js/bootstrap.min.js")
, 11540), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11615), Tuple.Create("\"", 11663)
, Tuple.Create(Tuple.Create("", 11621), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/common/common.min.js")
, 11621), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 213 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11731), Tuple.Create("\"", 11809)
, Tuple.Create(Tuple.Create("", 11737), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/jquery.easy-pie-chart/jquery.easy-pie-chart.min.js")
, 11737), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11833), Tuple.Create("\"", 11891)
, Tuple.Create(Tuple.Create("", 11839), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/jquery.gmap/jquery.gmap.min.js")
, 11839), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 11915), Tuple.Create("\"", 11981)
, Tuple.Create(Tuple.Create("", 11921), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/jquery.lazyload/jquery.lazyload.min.js")
, 11921), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12005), Tuple.Create("\"", 12062)
, Tuple.Create(Tuple.Create("", 12011), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/isotope/jquery.isotope.min.js")
, 12011), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12086), Tuple.Create("\"", 12146)
, Tuple.Create(Tuple.Create("", 12092), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/owl.carousel/owl.carousel.min.js")
, 12092), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12170), Tuple.Create("\"", 12241)
, Tuple.Create(Tuple.Create("", 12176), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/magnific-popup/jquery.magnific-popup.min.js")
, 12176), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12265), Tuple.Create("\"", 12309)
, Tuple.Create(Tuple.Create("", 12271), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/vide/vide.min.js")
, 12271), false)
);

WriteLiteral("></script>\r\n\r\n    <!-- Theme Base, Components and Settings -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12385), Tuple.Create("\"", 12417)
, Tuple.Create(Tuple.Create("", 12391), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/js/theme.js")
, 12391), false)
);

WriteLiteral("></script>\r\n\r\n    <!-- Current Page Vendor and Views -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12487), Tuple.Create("\"", 12558)
, Tuple.Create(Tuple.Create("", 12493), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/rs-plugin/js/jquery.themepunch.tools.min.js")
, 12493), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12582), Tuple.Create("\"", 12658)
, Tuple.Create(Tuple.Create("", 12588), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/rs-plugin/js/jquery.themepunch.revolution.min.js")
, 12588), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12682), Tuple.Create("\"", 12757)
, Tuple.Create(Tuple.Create("", 12688), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/circle-flip-slideshow/js/jquery.flipshow.min.js")
, 12688), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12781), Tuple.Create("\"", 12846)
, Tuple.Create(Tuple.Create("", 12787), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/nivo-slider/jquery.nivo.slider.min.js")
, 12787), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12870), Tuple.Create("\"", 12912)
, Tuple.Create(Tuple.Create("", 12876), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/js/views/view.home.js")
, 12876), false)
);

WriteLiteral("></script>\r\n\r\n    <!-- Tiny MCE -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12961), Tuple.Create("\"", 13029)
, Tuple.Create(Tuple.Create("", 12967), Tuple.Create<System.Object, System.Int32>(Href("~/assets/admin/plugins/bower_components/tinymce/tinymce.min.js")
, 12967), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 13053), Tuple.Create("\"", 13128)
, Tuple.Create(Tuple.Create("", 13059), Tuple.Create<System.Object, System.Int32>(Href("~/assets/admin/plugins/bower_components/tinymce/jquery.tinymce.min.js")
, 13059), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 13152), Tuple.Create("\"", 13223)
, Tuple.Create(Tuple.Create("", 13158), Tuple.Create<System.Object, System.Int32>(Href("~/assets/admin/plugins/bower_components/tinymce/tinymce-layout.js")
, 13158), false)
);

WriteLiteral("></script>\r\n    <!-- Theme Custom -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 13274), Tuple.Create("\"", 13307)
, Tuple.Create(Tuple.Create("", 13280), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/js/custom.js")
, 13280), false)
);

WriteLiteral("></script>\r\n\r\n    <!-- Theme Initialization Files -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 13374), Tuple.Create("\"", 13411)
, Tuple.Create(Tuple.Create("", 13380), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/js/theme.init.js")
, 13380), false)
);

WriteLiteral(@"></script>

    <!-- Google Analytics: Change UA-XXXXX-X to be your site's ID. Go to http://www.google.com/analytics/ for more information.
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-12345678-1', 'auto');
        ga('send', 'pageview');
    </script>
     -->
");

            
            #line 253 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 253 "..\..\Views\Shared\_Layout.cshtml"
     if (!CultureHelper.IsRighToLeft())
    {

            
            #line default
            #line hidden
WriteLiteral(@"        <script>
            jQuery(function ($) {
                $("".dropdown li"").on('mouseenter mouseleave', function (e) {
                    if ($('ul', this).length > 0) {
                        var elm = $('ul:first', this);
                        var off = elm.offset();
                        var l = off.left;
                        var w = elm.width();
                        var docW = $("".container"").width();
                        var isEntirelyVisible = (l + w <= docW + 100);
                        if (!isEntirelyVisible) {
                            $(this).addClass('edge');
                        } else {
                            $(this).removeClass('edge');
                        }
                    }
                });
            });
        </script>
");

            
            #line 274 "..\..\Views\Shared\_Layout.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral(@"        <script>
            jQuery(function ($) {
                $("".dropdown li"").on('mouseenter mouseleave', function (e) {
                    if ($('ul', this).length) {
                        var elm = $('ul:first', this);
                        var off = elm.offset();
                        var l = off.left;
                        var r = ($(window).width() - (elm.offset().left + elm.outerWidth()));
                        var w = elm.width();
                        var docW = $("".container"").width();
                        var isEntirelyVisible = (r + w <= docW + 100);
                        if (!isEntirelyVisible && !$(this).hasClass('edge')) {
                            $(this).addClass('edge');
                        }
                        else {
                            $(this).removeClass('edge');
                        }
                    }
                });
            });
        </script>
");

            
            #line 298 "..\..\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 299 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("Scripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
