#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cutecms_porto;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Identity/Views/Account/ForgotPasswordConfirmation.cshtml")]
    public partial class _Areas_Identity_Views_Account_ForgotPasswordConfirmation_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Identity_Views_Account_ForgotPasswordConfirmation_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Identity\Views\Account\ForgotPasswordConfirmation.cshtml"
  
    ViewBag.Title = Resources.Resources.ResetPasswordConfirmation;
    ViewBag.MainTitle = Resources.Resources.ResetPasswordConfirmation;
    ViewBag.SubTitle = Resources.Resources.ResetPasswordConfirmation;
    ViewBag.IconTitle = "fa fa-key";
    Layout = "~/Areas/Identity/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<section");

WriteLiteral(" class=\"page-header\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <h1>");

            
            #line 12 "..\..\Areas\Identity\Views\Account\ForgotPasswordConfirmation.cshtml"
               Write(Resources.Resources.ForgotPasswordConfirmation);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</section>\r\n<div>\r\n    <p>" +
"\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Areas\Identity\Views\Account\ForgotPasswordConfirmation.cshtml"
   Write(Resources.Resources.ForgotPasswordCheck);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
