#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cutecms_porto;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Identity/Views/Account/VerifyCode.cshtml")]
    public partial class _Areas_Identity_Views_Account_VerifyCode_cshtml : System.Web.Mvc.WebViewPage<cutecms_porto.Areas.Identity.Models.VerifyCodeViewModel>
    {
        public _Areas_Identity_Views_Account_VerifyCode_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
  
    ViewBag.Title = Resources.Resources.VerificationCode;
    ViewBag.MainTitle = Resources.Resources.VerificationCode;
    ViewBag.SubTitle = Resources.Resources.EnterVerificationCode;
    ViewBag.IconTitle = "fa fa-lock";
    Layout = "~/Areas/Identity/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 9 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
 using (Html.BeginForm("VerifyCode", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
Write(Html.Hidden("provider", @Model.Provider));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
                                             
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
Write(Html.Hidden("rememberMe", @Model.RememberMe));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
                                                 
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
       Write(Html.TextBoxFor(m => m.Code, new { @class = "form-control", @placeholder = Resources.Resources.VerificationCode + "..." }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n            <div>\r\n");

WriteLiteral("                ");

            
            #line 22 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
           Write(Html.CheckBoxFor(m => m.RememberBrowser));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 23 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
           Write(Html.LabelFor(m => m.RememberBrowser));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteAttribute("value", Tuple.Create(" value=\'", 1217), Tuple.Create("\'", 1252)
            
            #line 29 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
, Tuple.Create(Tuple.Create("", 1225), Tuple.Create<System.Object, System.Int32>(Resources.Resources.Verify
            
            #line default
            #line hidden
, 1225), false)
);

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral("/>\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 34 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
       Write(Html.ValidationSummary(false, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

            
            #line 37 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
}

            
            #line default
            #line hidden
DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 39 "..\..\Areas\Identity\Views\Account\VerifyCode.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
