#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 2 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cutecms_porto;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/RMS/Views/Vacancies/Details.cshtml")]
    public partial class _Areas_RMS_Views_Vacancies_Details_cshtml : System.Web.Mvc.WebViewPage<cutecms_porto.Areas.RMS.Models.DBModel.Vacancy>
    {
        public _Areas_RMS_Views_Vacancies_Details_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
  
    ViewBag.MainTitle = Resources.Resources.Vacancy;
    ViewBag.Title = Resources.Resources.Details;

            
            #line default
            #line hidden
WriteLiteral("\r\n<dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 9 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.LanguageId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayFor(model => model.Language.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.Code));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayFor(model => model.Code));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 21 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 24 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 27 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.Available));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 30 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayFor(model => model.Available));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 33 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 36 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.Raw(HttpUtility.HtmlDecode(Model.Description)));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.Requirements));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 42 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.Raw(HttpUtility.HtmlDecode(Model.Requirements)));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 45 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.Skills));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 48 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.Raw(HttpUtility.HtmlDecode(Model.Skills)));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 51 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.Documents));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 54 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.Raw(HttpUtility.HtmlDecode(Model.Documents)));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 57 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.JobTypeId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

            
            #line 60 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
        
            
            #line default
            #line hidden
            
            #line 60 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
           var jobType = Model.JobType.JobTypeTerms.Where(p => p.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name) && p.JobTypeId == Model.JobTypeId).FirstOrDefault()?.Value ?? Model.JobType.Code;
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 61 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(jobType);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 64 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.ProgramId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

            
            #line 67 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
        
            
            #line default
            #line hidden
            
            #line 67 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
           var program = Model.Program.ProgramTerms.Where(p => p.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name) && p.ProgramId == Model.ProgramId).FirstOrDefault()?.Value ?? Model.Program.Code;
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 68 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(program);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 71 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.StatusId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

            
            #line 74 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
        
            
            #line default
            #line hidden
            
            #line 74 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
           var status = Model.Status.StatusTerms.Where(p => p.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name) && p.StatusId == Model.StatusId).FirstOrDefault()?.Value ?? Model.Status.Code;
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 75 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(status);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 78 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.Author));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 81 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.Display("Author"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 84 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.ModifiedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 87 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.Display("ModifiedBy"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 90 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.CreatedOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 93 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayFor(model => model.CreatedOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 96 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.PublishedOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 99 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayFor(model => model.PublishedOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 102 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.ExpiredOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 105 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayFor(model => model.ExpiredOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 108 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.ModifiedOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 111 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayFor(model => model.ModifiedOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n    <dt>\r\n");

WriteLiteral("        ");

            
            #line 114 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayNameFor(model => model.IsTranslated));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dt>\r\n    <dd>\r\n");

WriteLiteral("        ");

            
            #line 117 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
   Write(Html.DisplayFor(model => model.IsTranslated));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </dd>\r\n</dl>\r\n<p>\r\n");

WriteLiteral("    ");

            
            #line 121 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
Write(Html.ActionLink(Resources.Resources.Edit, "Edit", new { id = Model.Id }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("    ");

            
            #line 122 "..\..\Areas\RMS\Views\Vacancies\Details.cshtml"
Write(Html.ActionLink(Resources.Resources.BackToList, "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>");

        }
    }
}
#pragma warning restore 1591
