#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cutecms_porto;
    
    #line 2 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
    using cutecms_porto.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/RMS/Views/Vacancies/Edit.cshtml")]
    public partial class _Areas_RMS_Views_Vacancies_Edit_cshtml : System.Web.Mvc.WebViewPage<cutecms_porto.Areas.RMS.Models.EditVacancyWithDRViewModel>
    {
        public _Areas_RMS_Views_Vacancies_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
  
    ViewBag.MainTitle = Resources.Resources.Vacancy;
    ViewBag.Title = Resources.Resources.Edit;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 9 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
   Write(Html.HiddenFor(model => model.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
   Write(Html.HiddenFor(model => model.LanguageId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
   Write(Html.HiddenFor(model => model.IsTranslated));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
   Write(Html.HiddenFor(model => model.TranslationId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
   Write(Html.HiddenFor(model => model.Author));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 16 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
   Write(Html.HiddenFor(model => model.CreatedOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 18 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.LanguageId, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 20 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.TextBox("LanguageId", null, new { @class = "form-control", @disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 24 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.Code, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 26 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 27 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 31 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 33 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 34 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 38 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.Available, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 40 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.EditorFor(model => model.Available, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 41 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 45 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 47 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.TextAreaFor(model => model.Description, new { @class = "mceEditor", @data_val = false }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 48 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 52 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.Requirements, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 54 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.TextAreaFor(model => model.Requirements, new { @class = "mceEditor" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 55 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Requirements, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 59 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.Skills, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 61 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.TextAreaFor(model => model.Skills, new { @class = "mceEditor" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 62 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Skills, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 66 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.Documents, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 68 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.TextAreaFor(model => model.Documents, new { @class = "mceEditor" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 69 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Documents, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 73 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.DeptId, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 75 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.DropDownList("DeptId", null, string.Empty, htmlAttributes: new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 76 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.DeptId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 80 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.JobTypeId, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 82 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.DropDownList("JobTypeId", null, string.Empty, htmlAttributes: new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 83 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.JobTypeId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 87 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.Degrees, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 89 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.EditorFor(model => model.Degrees, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 90 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Degrees, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 94 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.ProgramId, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 96 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.DropDownList("ProgramId", null, string.Empty, htmlAttributes: new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 97 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.ProgramId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 101 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.Ranks, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 103 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.EditorFor(model => model.Ranks, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 104 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Ranks, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 108 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.Notes, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 110 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.TextAreaFor(model => model.Notes, new { @class = "mceEditor" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 111 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 115 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.RoleVID, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 117 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.DropDownList("RoleVID", null, Resources.Resources.ChooseRole, htmlAttributes: new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 118 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.RoleVID, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 122 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.StatusId, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 124 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 125 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" id=\"PublishedOnDiv\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 129 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.PublishedOn, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 131 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.EditorFor(model => model.PublishedOn, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 132 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.PublishedOn, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" id=\"ExpiredOnDiv\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 136 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.ExpiredOn, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 138 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.EditorFor(model => model.ExpiredOn, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 139 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ValidationMessageFor(model => model.ExpiredOn, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 143 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.Author, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 145 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.TextBox("Author", null, htmlAttributes: new { @class = "form-control", @disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 146 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.HiddenFor(model => model.Author));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 150 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.ModifiedBy, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 152 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.TextBox("ModifiedBy", null, htmlAttributes: new { @class = "form-control", @disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 153 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.HiddenFor(model => model.ModifiedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 157 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.CreatedOn, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 159 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.TextBoxFor(model => model.CreatedOn, null, htmlAttributes: new { @class = "form-control", @disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 160 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.HiddenFor(model => model.CreatedOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 164 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.ModifiedOn, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 166 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.TextBoxFor(model => model.ModifiedOn, null, htmlAttributes: new { @class = "form-control", @disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 167 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.HiddenFor(model => model.ModifiedOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 171 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.PublishedOn, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 173 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.TextBoxFor(model => model.PublishedOn, null, htmlAttributes: new { @class = "form-control", @disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 174 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.HiddenFor(model => model.PublishedOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 178 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.LabelFor(model => model.ExpiredOn, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 180 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.TextBoxFor(model => model.ExpiredOn, null, htmlAttributes: new { @class = "form-control", @disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 181 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.HiddenFor(model => model.ExpiredOn));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteAttribute("value", Tuple.Create(" value=", 10570), Tuple.Create("", 10602)
            
            #line 186 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 10577), Tuple.Create<System.Object, System.Int32>(Resources.Resources.Save
            
            #line default
            #line hidden
, 10577), false)
);

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" />\r\n");

            
            #line 187 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 187 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
                 if (!Model.IsTranslated)
                {
                    
            
            #line default
            #line hidden
            
            #line 189 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
               Write(Html.ActionLink(Resources.Resources.AddTranslation, "Create", new { id = Model.TranslationId }, new { @class = "btn btn-info" }));

            
            #line default
            #line hidden
            
            #line 189 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
                                                                                                                                                     
                }
                else
                {
                    
            
            #line default
            #line hidden
            
            #line 193 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
               Write(Html.ActionLink(Resources.Resources.ViewTranslation, "Edit", new { id = Model.Id, translationId = Model.TranslationId, lang = Model.LanguageId }, new { @class = "btn btn-info" }));

            
            #line default
            #line hidden
            
            #line 193 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
                                                                                                                                                                                                       
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 195 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
           Write(Html.ActionLink(Resources.Resources.Delete, "Delete", new { id = Model.Id }, new { @class = "btn btn-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 201 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
       Write(Html.ValidationSummary(false, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

            
            #line 204 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n");

WriteLiteral("    ");

            
            #line 206 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
Write(Html.ActionLink(Resources.Resources.BackToList, "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 209 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $('#PublishedOn').removeAttr(""data-val-date"");
        $('#ExpiredOn').removeAttr(""data-val-date"");
        $('#StartDate').removeAttr(""data-val-date"");
        $('#EndDate').removeAttr(""data-val-date"");
        $('#ModifiedOn').removeAttr(""data-val-date"");
        $('#CreatedOn').removeAttr(""data-val-date"");
    </script>
");

            
            #line 218 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 218 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
     if (CultureHelper.IsRighToLeft())
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
            $('#PublishedOn').datetimepicker({
                showClose: true,
                showClear: true,
                showTodayButton: true,
                useCurrent: true,
                format: ""DD/MM/YYYY LT"",
                widgetPositioning: {
                    horizontal: 'right'
                }
            });
            $('#ExpiredOn').datetimepicker({
                showClose: true,
                showClear: true,
                showTodayButton: true,
                useCurrent: false,
                format: ""DD/MM/YYYY LT"",
                widgetPositioning: {
                    horizontal: 'right'
                }
            });
            $(""#PublishedOn"").on(""dp.change"", function (e) {
                $('#ExpiredOn').data(""DateTimePicker"").minDate(e.date);
            });
            $(""#ExpiredOn"").on(""dp.change"", function (e) {
                $('#PublishedOn').data(""DateTimePicker"").maxDate(e.date);
            });
        </script>
");

            
            #line 248 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
            $('#PublishedOn').datetimepicker({
                showClose: true,
                showClear: true,
                showTodayButton: true,
                useCurrent: true
            });
            $('#ExpiredOn').datetimepicker({
                showClose: true,
                showClear: true,
                showTodayButton: true,
                useCurrent: false
            });
            $(""#PublishedOn"").on(""dp.change"", function (e) {
                $('#ExpiredOn').data(""DateTimePicker"").minDate(e.date);
            });
            $(""#ExpiredOn"").on(""dp.change"", function (e) {
                $('#PublishedOn').data(""DateTimePicker"").maxDate(e.date);
            });
        </script>
");

            
            #line 271 "..\..\Areas\RMS\Views\Vacancies\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(""#ExpiredOnDiv"").hide();
        $(""#PublishedOnDiv"").hide();
        var selectedValue = $(""#StatusId"").val();
        if (selectedValue == 1) {
            $(""#ExpiredOnDiv"").fadeIn();
        }
        if (selectedValue == 3) {
            $(""#PublishedOnDiv"").fadeIn();
            $(""#ExpiredOnDiv"").fadeIn();
        }
        $(function () {
            $(""#StatusId"").change(function () {
                var selectedText = $(this).find(""option:selected"").text();
                var selectedValue = $(this).val();
                if (selectedValue == 1) {
                    $(""#PublishedOnDiv"").fadeOut();
                    $(""#ExpiredOnDiv"").fadeIn();
                    $(""#PublishedOn"").val(null);
                }
                if (selectedValue == 2) {
                    $(""#ExpiredOnDiv"").fadeOut();
                    $(""#PublishedOnDiv"").fadeOut();
                    $(""#PublishedOn"").val(null);
                    $(""#ExpiredOn"").val(null);
                }
                if (selectedValue == 3) {
                    $(""#ExpiredOnDiv"").fadeIn();
                    $(""#PublishedOnDiv"").fadeIn();
                    $(""#PublishedOn"").val(null);
                    $(""#ExpiredOn"").val(null);
                }
                //alert(""Selected Text: "" + selectedText + "" Value: "" + selectedValue);
            });
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
