#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cutecms_porto;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/RMS/Views/Attachments/Details.cshtml")]
    public partial class _Areas_RMS_Views_Attachments_Details_cshtml : System.Web.Mvc.WebViewPage<cutecms_porto.Areas.RMS.Models.DBModel.Attachment>
    {
        public _Areas_RMS_Views_Attachments_Details_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\RMS\Views\Attachments\Details.cshtml"
  
    ViewBag.MainTitle = Resources.Resources.Attachment;
    ViewBag.Title = Resources.Resources.Details;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div>\r\n    <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 9 "..\..\Areas\RMS\Views\Attachments\Details.cshtml"
       Write(Html.DisplayNameFor(model => model.FilePath));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 12 "..\..\Areas\RMS\Views\Attachments\Details.cshtml"
       Write(Html.DisplayFor(model => model.FilePath));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Areas\RMS\Views\Attachments\Details.cshtml"
       Write(Html.DisplayNameFor(model => model.Applicant.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 18 "..\..\Areas\RMS\Views\Attachments\Details.cshtml"
       Write(Html.DisplayFor(model => model.Applicant.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n    </dl>\r\n</div>\r\n<p>\r\n");

WriteLiteral("    ");

            
            #line 23 "..\..\Areas\RMS\Views\Attachments\Details.cshtml"
Write(Html.ActionLink(Resources.Resources.Edit, "Edit", new { /* id = Model.PrimaryKey */ }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("    ");

            
            #line 24 "..\..\Areas\RMS\Views\Attachments\Details.cshtml"
Write(Html.ActionLink(Resources.Resources.BackToList, "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>");

        }
    }
}
#pragma warning restore 1591
