#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cutecms_porto;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Identity/Views/Manage/Index.cshtml")]
    public partial class _Areas_Identity_Views_Manage_Index_cshtml : System.Web.Mvc.WebViewPage<cutecms_porto.Areas.Identity.Models.ManageViewModel>
    {
        public _Areas_Identity_Views_Manage_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
  
    ViewBag.Title = Resources.Resources.AccountSettings;
    ViewBag.MainTitle = Resources.Resources.AccountSettings;
    ViewBag.SubTitle = Resources.Resources.ChangeAccountSettings;
    ViewBag.IconTitle = "fa fa-user";
    Layout = "~/Areas/Identity/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 9 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
 using (Html.BeginForm("Index", "Manage", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 13 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
       Write(Html.ActionLink(Resources.Resources.ExploreOurSite, "Index", "Home", new { area = "" }, null));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <br />\r\n");

            
            #line 15 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
             if (User.IsInRole("Admin"))
            {
                
            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
           Write(Html.ActionLink(Resources.Resources.GoCuteCMS, "Index", "Home", new { area = "CMS" }, null));

            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
                                                                                                            
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 23 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
       Write(Html.Label(Resources.Resources.Password));

            
            #line default
            #line hidden
WriteLiteral(":\r\n");

            
            #line 24 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
             if (Model.HasPassword)
                {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("[");

            
            #line 26 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
              Write(Html.ActionLink(Resources.Resources.ChangePassword, "ChangePassword"));

            
            #line default
            #line hidden
WriteLiteral("]\r\n");

            
            #line 27 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
            }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("[ ");

            
            #line 30 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
               Write(Html.ActionLink(Resources.Resources.SetPassword, "SetPassword"));

            
            #line default
            #line hidden
WriteLiteral("]\r\n");

            
            #line 31 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
                 }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 36 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
       Write(Html.Label(Resources.Resources.ExternalLogins));

            
            #line default
            #line hidden
WriteLiteral(":\r\n            [");

            
            #line 37 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
        Write(Model.Logins.Count);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 37 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
                            Write(Html.ActionLink(Resources.Resources.ManageLogins, "ManageLogins"));

            
            #line default
            #line hidden
WriteLiteral("]\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 42 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
       Write(Html.Label(Resources.Resources.PhoneNumber));

            
            #line default
            #line hidden
WriteLiteral(":\r\n");

WriteLiteral("            ");

            
            #line 43 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
        Write(Model.PhoneNumber ?? Resources.Resources.NotAvailable);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 44 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 44 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
             if (Model.PhoneNumber != null)
                {
            
            #line default
            #line hidden
WriteLiteral("[\r\n");

            
            #line 46 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 46 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
           Write(Html.ActionLink(Resources.Resources.Edit, "AddPhoneNumber"));

            
            #line default
            #line hidden
            
            #line 46 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
                                                                            

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral(" &nbsp;|&nbsp;\r\n");

            
            #line 48 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 48 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
           Write(Html.ActionLink(Resources.Resources.Delete, "RemovePhoneNumber"));

            
            #line default
            #line hidden
            
            #line 48 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
                                                                                 

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("]\r\n");

            
            #line 50 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
            }
                else
                {
                
            
            #line default
            #line hidden
            
            #line 53 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
           Write(Html.ActionLink(Resources.Resources.Create, "AddPhoneNumber"));

            
            #line default
            #line hidden
            
            #line 53 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
                                                                              
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n");

            
            #line 57 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
}

            
            #line default
            #line hidden
            
            #line 58 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
 if (Model.TwoFactor)
{
    using (Html.BeginForm("DisableTwoFactorAuthentication", "Manage", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        
            
            #line default
            #line hidden
            
            #line 62 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 62 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 65 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
           Write(Html.Label(Resources.Resources.TwoFactor));

            
            #line default
            #line hidden
WriteLiteral(":\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteAttribute("value", Tuple.Create(" value=", 2655), Tuple.Create("", 2690)
            
            #line 66 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2662), Tuple.Create<System.Object, System.Int32>(Resources.Resources.Disable
            
            #line default
            #line hidden
, 2662), false)
);

WriteLiteral(" class=\"btn \"");

WriteLiteral(" style=\"color:dimgrey\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n");

            
            #line 69 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
    }
}
else
{
    using (Html.BeginForm("EnableTwoFactorAuthentication", "Manage", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        
            
            #line default
            #line hidden
            
            #line 75 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 75 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 78 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
           Write(Html.Label(Resources.Resources.TwoFactor));

            
            #line default
            #line hidden
WriteLiteral(":\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteAttribute("value", Tuple.Create(" value=", 3133), Tuple.Create("", 3167)
            
            #line 79 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3140), Tuple.Create<System.Object, System.Int32>(Resources.Resources.Enable
            
            #line default
            #line hidden
, 3140), false)
);

WriteLiteral(" class=\"btn \"");

WriteLiteral(" style=\"color:dimgrey\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n");

            
            #line 82 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
    }
}

            
            #line default
            #line hidden
DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 85 "..\..\Areas\Identity\Views\Manage\Index.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
