#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cutecms_porto;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Identity/Views/Publications/Index.cshtml")]
    public partial class _Areas_Identity_Views_Publications_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<cutecms_porto.Areas.Identity.Models.DBModel.Publication>>
    {
        public _Areas_Identity_Views_Publications_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
  
    ViewBag.MainTitle = Resources.Resources.Publications;
    ViewBag.Title = Resources.Resources.Index;

            
            #line default
            #line hidden
WriteLiteral("\r\n<p>\r\n");

WriteLiteral("    ");

            
            #line 7 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
Write(Html.ActionLink(Resources.Resources.Create, "Create", new { id = ViewBag.EmpId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n    <tr>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 12 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.EmpId));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 18 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Ordinal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th></th>\r\n    </tr>\r\n");

            
            #line 22 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
     foreach (var item in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 26 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
           Write(Html.DisplayFor(modelItem => item.Employee.FullName));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 29 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
           Write(Html.DisplayFor(modelItem => item.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
           Write(Html.DisplayFor(modelItem => item.Ordinal));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 35 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
           Write(Html.ActionLink(Resources.Resources.Edit, "Edit", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("                ");

            
            #line 36 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
           Write(Html.ActionLink(Resources.Resources.Details, "Details", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("                ");

            
            #line 37 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
           Write(Html.ActionLink(Resources.Resources.Delete, "Delete", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n");

            
            #line 40 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 43 "..\..\Areas\Identity\Views\Publications\Index.cshtml"
Write(Html.ActionLink(Resources.Resources.BackToList, "Index", "Employees"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
