#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 3 "..\..\Views\Home\Calendar.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cutecms_porto;
    
    #line 2 "..\..\Views\Home\Calendar.cshtml"
    using cutecms_porto.Areas.CMS.Models.DBModel;
    
    #line default
    #line hidden
    using cutecms_porto.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Calendar.cshtml")]
    public partial class _Views_Home_Calendar_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<cutecms_porto.Areas.CMS.Models.DBModel.Content>>
    {
        public _Views_Home_Calendar_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Home\Calendar.cshtml"
  
    ViewBag.Title = Resources.Resources.Calendar;
    string langFile = CultureHelper.GetCurrentNeutralCulture();
    CMSEntities db = new CMSEntities();

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("PageHeader", () => {

WriteLiteral("\r\n    <section");

WriteLiteral(" class=\"page-header\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                    <h1>");

            
            #line 15 "..\..\Views\Home\Calendar.cshtml"
                   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </section>" +
"\r\n");

});

DefineSection("Styles", () => {

WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 619), Tuple.Create("\"", 681)
, Tuple.Create(Tuple.Create("", 626), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/fullcalendar/fullcalendar.min.css")
, 626), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 713), Tuple.Create("\"", 783)
, Tuple.Create(Tuple.Create("", 720), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/jquery-ui-1.12.1.custom/jquery-ui.min.css")
, 720), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

});

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 839), Tuple.Create("\"", 897)
, Tuple.Create(Tuple.Create("", 845), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/fullcalendar/lib/moment.min.js")
, 845), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 921), Tuple.Create("\"", 981)
, Tuple.Create(Tuple.Create("", 927), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/fullcalendar/fullcalendar.min.js")
, 927), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1005), Tuple.Create("\"", 1059)
, Tuple.Create(Tuple.Create("", 1011), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/fullcalendar/locale-all.js")
, 1011), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1083), Tuple.Create("\"", 1151)
, Tuple.Create(Tuple.Create("", 1089), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/jquery-ui-1.12.1.custom/jquery-ui.min.js")
, 1089), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("<section");

WriteLiteral(" class=\"justify\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"calendar\"");

WriteLiteral(" class=\"col-lg-8\"");

WriteLiteral(">\r\n                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
                    function GetCurrentDate() {
                        var date = new Date();
                        var yyyy = date.getFullYear().toString();
                        var mm = (date.getMonth() + 1).toString();
                        var dd = date.getDate().toString();
                        return yyyy + '-' + (mm[1] ? mm : ""0"" + mm[0]) + '-' + (dd[1] ? dd : ""0"" + dd[0]);
                    }
                    $(document).ready(function () {
                        $('#calendar').fullCalendar({
                            theme: true,
                            locale: '");

            
            #line 46 "..\..\Views\Home\Calendar.cshtml"
                                Write(langFile);

            
            #line default
            #line hidden
WriteLiteral(@"',
                            header: {
                                left: 'prev,next,today',
                                center: 'title',
                                right: 'month,agendaWeek,agendaDay'
                            },
                            viewRender: function (view, element) {

                                $('#calendar table').css('background-color', 'transparent');

                                $('#calendar tr.fc-minor').attr('style', 'background:initial;');

                                $('#calendar table').css('margin-bottom', '0');

                            },
                            defaultDate: GetCurrentDate(),
                            events: """);

            
            #line 62 "..\..\Views\Home\Calendar.cshtml"
                                Write(Url.Action("ListEvents"));

            
            #line default
            #line hidden
WriteLiteral(@""",
                            droppable: false,
                            editable: false,
                            eventRender: function (event, element) {
                                element.attr('Title', event.title);
                                if (event.location != null) {
                                    element.find('.fc-title').append(""<hr>"" + event.location);
                                }
                            },
                            eventClick: function (calEvent, jsEvent, view) {
                                window.location = ""/"" + """);

            
            #line 72 "..\..\Views\Home\Calendar.cshtml"
                                                    Write(Thread.CurrentThread.CurrentCulture.Name);

            
            #line default
            #line hidden
WriteLiteral("\" + \"/home/contents?contentTypeIdFilter=\" + \"");

            
            #line 72 "..\..\Views\Home\Calendar.cshtml"
                                                                                                                                          Write(db.ContentTypes.Where(c=>c.Code.Trim().Equals("event")).FirstOrDefault().Id);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n                            }\r\n                        });\r\n                 " +
"   });\r\n                </script>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-lg-4\"");

WriteLiteral(">\r\n                <h2>");

            
            #line 79 "..\..\Views\Home\Calendar.cshtml"
               Write(Resources.Resources.UpcomingEvents);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 80 "..\..\Views\Home\Calendar.cshtml"
                
            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\Home\Calendar.cshtml"
                 if (Model.Count() > 0)
            {
                foreach (var item in Model)
                {

            
            #line default
            #line hidden
WriteLiteral("                        <div>\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3898), Tuple.Create("\"", 3965)
            
            #line 85 "..\..\Views\Home\Calendar.cshtml"
, Tuple.Create(Tuple.Create("", 3905), Tuple.Create<System.Object, System.Int32>(Url.Action("Content", "Pages" , new { slug=@item.UrlSlug })
            
            #line default
            #line hidden
, 3905), false)
);

WriteLiteral(">");

            
            #line 85 "..\..\Views\Home\Calendar.cshtml"
                                                                                              Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</a><br />\r\n");

            
            #line 86 "..\..\Views\Home\Calendar.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 86 "..\..\Views\Home\Calendar.cshtml"
                             if (item.StartDate != null)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <small");

WriteLiteral(" class=\"text-danger text-small\"");

WriteLiteral(">");

            
            #line 88 "..\..\Views\Home\Calendar.cshtml"
                                                                 Write(Resources.Resources.From);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 88 "..\..\Views\Home\Calendar.cshtml"
                                                                                           Write(item.StartDate.Value.ToString("dddd, d MMMM, yyyy | h:mm tt"));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 88 "..\..\Views\Home\Calendar.cshtml"
                                                                                                                                                           Write(item.EndDate == null ? "" : @Resources.Resources.Till + " " + item.EndDate.Value.ToString("dddd, d MMMM, yyyy | h:mm tt"));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 88 "..\..\Views\Home\Calendar.cshtml"
                                                                                                                                                                                                                                                                                        Write(item.Location == null ? "" : "@ " + item.Location);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n");

            
            #line 89 "..\..\Views\Home\Calendar.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n");

WriteLiteral("                        <small>");

            
            #line 91 "..\..\Views\Home\Calendar.cshtml"
                          Write(item.MainContent.StripHtml().Chop(155));

            
            #line default
            #line hidden
WriteLiteral("<br /><a");

WriteLiteral(" class=\"btn btn-reveal btn-info btn-xs\"");

WriteAttribute("href", Tuple.Create(" href=\"", 4605), Tuple.Create("\"", 4672)
            
            #line 91 "..\..\Views\Home\Calendar.cshtml"
                                            , Tuple.Create(Tuple.Create("", 4612), Tuple.Create<System.Object, System.Int32>(Url.Action("Content", "Pages" , new { slug=@item.UrlSlug })
            
            #line default
            #line hidden
, 4612), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-plus\"");

WriteLiteral("></i><span>");

            
            #line 91 "..\..\Views\Home\Calendar.cshtml"
                                                                                                                                                                                                                     Write(Resources.Resources.ReadMore);

            
            #line default
            #line hidden
WriteLiteral("</span></a></small>\r\n");

WriteLiteral("                        <hr />\r\n");

            
            #line 93 "..\..\Views\Home\Calendar.cshtml"
                    }
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <p>");

            
            #line 97 "..\..\Views\Home\Calendar.cshtml"
                  Write(Resources.Resources.NoUpcomingEvents);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 98 "..\..\Views\Home\Calendar.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</section>");

        }
    }
}
#pragma warning restore 1591
