#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 4 "..\..\Views\Home\Galleries.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cutecms_porto;
    
    #line 5 "..\..\Views\Home\Galleries.cshtml"
    using cutecms_porto.Areas.CMS.Models.DBModel;
    
    #line default
    #line hidden
    using cutecms_porto.Helpers;
    
    #line 3 "..\..\Views\Home\Galleries.cshtml"
    using PagedList;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Home\Galleries.cshtml"
    using PagedList.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Galleries.cshtml")]
    public partial class _Views_Home_Galleries_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<cutecms_porto.Areas.CMS.Models.DBModel.Gallery>>
    {
        public _Views_Home_Galleries_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Home\Galleries.cshtml"
  
    List<string> categoryList = new List<string>();
    ViewBag.Title = @Resources.Resources.PhotoGallery;
    CMSEntities cmsDb = new CMSEntities();

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("PageHeader", () => {

WriteLiteral("\r\n    <section");

WriteLiteral(" class=\"page-header\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                    <h1>");

            
            #line 17 "..\..\Views\Home\Galleries.cshtml"
                   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </section>" +
"\r\n");

});

WriteLiteral("<section>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"nav nav-pills sort-source\"");

WriteLiteral(" data-sort-id=\"portfolio\"");

WriteLiteral(" data-option-key=\"filter\"");

WriteLiteral(">\r\n                <li");

WriteLiteral(" data-option-value=\"*\"");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 27 "..\..\Views\Home\Galleries.cshtml"
                                                                Write(Resources.Resources.ShowAll);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 28 "..\..\Views\Home\Galleries.cshtml"
                
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Home\Galleries.cshtml"
                 foreach (var item in Model)
                {
                    var galleryCategories = item.GalleryCategories.Select(g => g.Category.Code).ToList();
                    foreach (var galleryCategory in galleryCategories)
                    {
                        categoryList.Add(galleryCategory);
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 36 "..\..\Views\Home\Galleries.cshtml"
                   var uniqueItems = new HashSet<string>(categoryList);
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 37 "..\..\Views\Home\Galleries.cshtml"
                
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Home\Galleries.cshtml"
                 foreach (var category in uniqueItems)
                {
                    string categoryName = cmsDb.CategoryTerms.Where(c => c.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name) && c.Category.Code.Equals(category)).FirstOrDefault()?.Value;

            
            #line default
            #line hidden
WriteLiteral("                    <li");

WriteLiteral(" data-option-value=\".");

            
            #line 40 "..\..\Views\Home\Galleries.cshtml"
                                       Write(category);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 40 "..\..\Views\Home\Galleries.cshtml"
                                                               Write(categoryName ?? category);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 41 "..\..\Views\Home\Galleries.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n            <hr>\r\n\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"sort-destination-loader sort-destination-loader-showing\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"image-gallery sort-destination lightbox\"");

WriteLiteral(" data-sort-id=\"portfolio\"");

WriteLiteral(" data-plugin-options=\'{\"delegate\": \"a.lightbox-portfolio\", \"type\": \"image\", \"gall" +
"ery\": {\"enabled\": true}}\'");

WriteLiteral(">\r\n\r\n");

            
            #line 50 "..\..\Views\Home\Galleries.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Home\Galleries.cshtml"
                         foreach (var item in Model)
                        {
                            string categoryFilters = string.Join(" ", item.GalleryCategories.Select(g => g.Category.Code).ToList());

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2377), Tuple.Create("\"", 2442)
, Tuple.Create(Tuple.Create("", 2385), Tuple.Create("col-md-3", 2385), true)
, Tuple.Create(Tuple.Create(" ", 2393), Tuple.Create("col-sm-6", 2394), true)
, Tuple.Create(Tuple.Create(" ", 2402), Tuple.Create("col-xs-12", 2403), true)
, Tuple.Create(Tuple.Create(" ", 2412), Tuple.Create("isotope-item", 2413), true)
            
            #line 53 "..\..\Views\Home\Galleries.cshtml"
, Tuple.Create(Tuple.Create(" ", 2425), Tuple.Create<System.Object, System.Int32>(categoryFilters
            
            #line default
            #line hidden
, 2426), false)
);

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"image-gallery-item\"");

WriteLiteral(">\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2550), Tuple.Create("\"", 2622)
            
            #line 55 "..\..\Views\Home\Galleries.cshtml"
, Tuple.Create(Tuple.Create("", 2557), Tuple.Create<System.Object, System.Int32>(Url.Action("ImageFiles","Home", new { id = item.Id, area = "" })
            
            #line default
            #line hidden
, 2557), false)
);

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"thumb-info\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"thumb-info-wrapper\"");

WriteLiteral(">\r\n                                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2824), Tuple.Create("\"", 2895)
            
            #line 58 "..\..\Views\Home\Galleries.cshtml"
, Tuple.Create(Tuple.Create("", 2830), Tuple.Create<System.Object, System.Int32>(item.ImageFiles.OrderBy(i=>i.Ordinal).FirstOrDefault().ThumbPath
            
            #line default
            #line hidden
, 2830), false)
);

WriteLiteral(" class=\"img-responsive\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"thumb-info-title\"");

WriteLiteral(">\r\n");

            
            #line 60 "..\..\Views\Home\Galleries.cshtml"
                                                    
            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\Home\Galleries.cshtml"
                                                      
                                                        string gallery = item.GalleryTerms.Where(g => g.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name) && g.GalleryId == item.Id).FirstOrDefault()?.Value ?? item.Code;
                                                        string galleryDescription = item.GalleryTerms.Where(g => g.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name) && g.GalleryId == item.Id).FirstOrDefault()?.Description;
                                                    
            
            #line default
            #line hidden
WriteLiteral("\r\n                                                    <span");

WriteLiteral(" class=\"thumb-info-inner\"");

WriteLiteral(">");

            
            #line 64 "..\..\Views\Home\Galleries.cshtml"
                                                                              Write(galleryDescription);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                                    <span");

WriteLiteral(" class=\"thumb-info-type\"");

WriteLiteral(">");

            
            #line 65 "..\..\Views\Home\Galleries.cshtml"
                                                                             Write(gallery);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                                </span>\r\n               " +
"                                 <span");

WriteLiteral(" class=\"thumb-info-action\"");

WriteLiteral(">\r\n                                                    <span");

WriteLiteral(" class=\"thumb-info-action-icon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-link\"");

WriteLiteral(@"></i></span>
                                                </span>
                                            </span>
                                        </span>
                                    </a>
                                </div>
                            </li>
");

            
            #line 75 "..\..\Views\Home\Galleries.cshtml"
                                                        }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\r\n                </div>\r\n            </div>\r\n        </" +
"div>\r\n    </div>\r\n</section>\r\n");

            
            #line 82 "..\..\Views\Home\Galleries.cshtml"
Write(Html.PagedListPager((IPagedList)Model, page => Url.Action("Galleries", new { page })));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
