#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 3 "..\..\Views\Home\Index.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cutecms_porto;
    
    #line 1 "..\..\Views\Home\Index.cshtml"
    using cutecms_porto.Areas.CMS.Models.DBModel;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Home\Index.cshtml"
    using cutecms_porto.Areas.Identity.Models.DBModel;
    
    #line default
    #line hidden
    using cutecms_porto.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<cutecms_porto.Models.HomeViewModel>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Home\Index.cshtml"
  
    CMSEntities cmsDb = new CMSEntities();
    IdentityEntities IdentityDb = new IdentityEntities();
    var openingHours = Model.ContentLists.Where(c => c.Code.Trim().Equals("opening-hours")).FirstOrDefault()?.ListItems ?? new List<ListItem>();
    var shortcutContents = Model.Contents.Where(c => c.HasShortcut);
    var insuranceList = Model.ContentLists.Where(c => c.Code.Trim().Equals("insurance"))?.FirstOrDefault() ?? new ContentList();
    var resourcesList = Model.ContentLists.Where(c => c.Code.Trim().Equals("resources"))?.FirstOrDefault() ?? new ContentList();

    IdentityEntities identityDb = new IdentityEntities();


            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Styles", () => {

WriteLiteral("\r\n    <!-- Current Page CSS -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 891), Tuple.Create("\"", 946)
, Tuple.Create(Tuple.Create("", 898), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/rs-plugin/css/settings.css")
, 898), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 976), Tuple.Create("\"", 1029)
, Tuple.Create(Tuple.Create("", 983), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/rs-plugin/css/layers.css")
, 983), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1059), Tuple.Create("\"", 1116)
, Tuple.Create(Tuple.Create("", 1066), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/vendor/rs-plugin/css/navigation.css")
, 1066), false)
);

WriteLiteral(">\r\n\r\n");

});

WriteLiteral("<div");

WriteLiteral(" class=\"slider-container rev_slider_wrapper\"");

WriteLiteral(" style=\"height: 650px;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"revolutionSlider\"");

WriteLiteral(" class=\"slider rev_slider\"");

WriteLiteral(" data-plugin-revolution-slider");

WriteLiteral(@" data-plugin-options=""{'delay': 9000, 'gridwidth': 1170, 'gridheight': 650, 'disableProgressBar': 'on', 'navigation': {'bullets': {'enable': true, 'direction': 'vertical', 'h_align': 'right', 'v_align': 'center', 'space': 5}, 'arrows': {'enable': false}}}""");

WriteLiteral(">\r\n        <ul>\r\n");

            
            #line 26 "..\..\Views\Home\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Home\Index.cshtml"
             foreach (var item in Model.HomeGallery)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" data-transition=\"fade\"");

WriteLiteral(">\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1696), Tuple.Create("\"", 1716)
            
            #line 29 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1702), Tuple.Create<System.Object, System.Int32>(item.FilePath
            
            #line default
            #line hidden
, 1702), false)
);

WriteAttribute("alt", Tuple.Create("\r\n                         alt=\"", 1717), Tuple.Create("\"", 1930)
            
            #line 30 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1749), Tuple.Create<System.Object, System.Int32>(item.ImageFileTerms.Where(it => it.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name) && it.ImageFileId == item.Id).FirstOrDefault()?.Value ?? item.Code
            
            #line default
            #line hidden
, 1749), false)
);

WriteLiteral("\r\n                         data-bgposition=\"center center\"");

WriteLiteral("\r\n                         data-bgfit=\"cover\"");

WriteLiteral("\r\n                         data-bgrepeat=\"no-repeat\"");

WriteLiteral("\r\n                         class=\"rev-slidebg\"");

WriteLiteral(">\r\n\r\n                    <div");

WriteLiteral(" class=\"tp-caption main-label\"");

WriteLiteral("\r\n                         data-x=\"left\"");

WriteLiteral(" data-hoffset=\"25\"");

WriteLiteral("\r\n                         data-y=\"center\"");

WriteLiteral(" data-voffset=\"-5\"");

WriteLiteral("\r\n                         data-start=\"1500\"");

WriteLiteral("\r\n                         data-whitespace=\"nowrap\"");

WriteLiteral("\r\n                         data-transform_in=\"y:[100%];s:500;\"");

WriteLiteral("\r\n                         data-transform_out=\"opacity:0;s:500;\"");

WriteLiteral("\r\n                         style=\"z-index: 5; font-size: 1.5em; text-transform: u" +
"ppercase;\"");

WriteLiteral("\r\n                         data-mask_in=\"x:0px;y:0px;\"");

WriteLiteral(">");

            
            #line 44 "..\..\Views\Home\Index.cshtml"
                                                 Write(item.ImageFileTerms.Where(it => it.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name) && it.ImageFileId == item.Id).FirstOrDefault()?.SecondaryCaption);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n                        <div");

WriteLiteral(" class=\"tp-caption main-label\"");

WriteLiteral("\r\n                             data-x=\"left\"");

WriteLiteral(" data-hoffset=\"25\"");

WriteLiteral("\r\n                             data-y=\"center\"");

WriteLiteral(" data-voffset=\"-55\"");

WriteLiteral("\r\n                             data-start=\"500\"");

WriteLiteral("\r\n                             style=\"z-index: 5; text-transform: uppercase; font" +
"-size: 52px;\"");

WriteLiteral("\r\n                             data-transform_in=\"y:[-300%];opacity:0;s:500;\"");

WriteLiteral(">");

            
            #line 51 "..\..\Views\Home\Index.cshtml"
                                                                        Write(item.ImageFileTerms.Where(it => it.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name) && it.ImageFileId == item.Id).FirstOrDefault()?.PrimaryCaption);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n                            <div");

WriteLiteral(" class=\"tp-caption bottom-label\"");

WriteLiteral("\r\n                                 data-x=\"left\"");

WriteLiteral(" data-hoffset=\"25\"");

WriteLiteral("\r\n                                 data-y=\"center\"");

WriteLiteral(" data-voffset=\"40\"");

WriteLiteral("\r\n                                 data-start=\"2000\"");

WriteLiteral("\r\n                                 style=\"z-index: 5; border-bottom: 1px solid #f" +
"ff; padding-bottom: 3px;\"");

WriteLiteral("\r\n                                 data-transform_in=\"y:[100%];opacity:0;s:500;\"");

WriteLiteral(" style=\"font-size: 1.2em;\"");

WriteLiteral(">");

            
            #line 58 "..\..\Views\Home\Index.cshtml"
                                                                                                     Write(item.ImageFileTerms.Where(it => it.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name) && it.ImageFileId == item.Id).FirstOrDefault()?.TertiaryCaption);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            </li>\r\n");

            
            #line 60 "..\..\Views\Home\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n    </div>\r\n</div>\r\n<section");

WriteLiteral(" class=\"section-custom-medical\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row medical-schedules\"");

WriteLiteral(">\r\n");

            
            #line 67 "..\..\Views\Home\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Home\Index.cshtml"
             if (cutecms_porto.Helpers.CultureHelper.IsRighToLeft())
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"col-lg-3 box-four background-color-secondary p-none appear-animation\"");

WriteLiteral(" data-appear-animation=\"fadeInLeft\"");

WriteLiteral(" data-appear-animation-delay=\"1800\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"tel:+008001234567\"");

WriteLiteral(" class=\"text-decoration-none\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"feature-box feature-box-style-2 m-none\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"feature-box-icon\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"icon-call-out icons\"");

WriteLiteral("></i>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"feature-box-info ml-md\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"font-weight-light\"");

WriteLiteral(">");

            
            #line 76 "..\..\Views\Home\Index.cshtml"
                                                            Write(Resources.Resources.EmergencyCase);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                <strong");

WriteLiteral(" class=\"font-weight-normal\"");

WriteLiteral(">");

            
            #line 77 "..\..\Views\Home\Index.cshtml"
                                                               Write(OrganizationData.Organization?.Telephone);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                            </div>\r\n                        </div>\r\n  " +
"                  </a>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"col-lg-3 box-three background-color-primary appear-animation\"");

WriteLiteral(" data-appear-animation=\"fadeInLeft\"");

WriteLiteral(" data-appear-animation-delay=\"1200\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"expanded-info p-xlg background-color-primary\"");

WriteLiteral(">\r\n");

            
            #line 84 "..\..\Views\Home\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 84 "..\..\Views\Home\Index.cshtml"
                         foreach (var item in openingHours)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"info custom-info log-in-info\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(" class=\"bold\"");

WriteLiteral(">");

            
            #line 87 "..\..\Views\Home\Index.cshtml"
                                                                 Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                <div");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">");

            
            #line 88 "..\..\Views\Home\Index.cshtml"
                                                    Write(item.Subtitle);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            </div>\r\n");

            
            #line 90 "..\..\Views\Home\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                    <h5");

WriteLiteral(" class=\"m-none\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 93 "..\..\Views\Home\Index.cshtml"
                   Write(Resources.Resources.OpeningHours);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <i");

WriteLiteral(" class=\"icon-arrow-right-circle icons\"");

WriteLiteral("></i>\r\n                    </h5>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"col-lg-3 box-two background-color-tertiary appear-animation\"");

WriteLiteral(" data-appear-animation=\"fadeInLeft\"");

WriteLiteral(" data-appear-animation-delay=\"600\"");

WriteLiteral(">\r\n                    <h5");

WriteLiteral(" class=\"m-none\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"demo-medical-doctors.html\"");

WriteLiteral(" title=\"\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 100 "..\..\Views\Home\Index.cshtml"
                       Write(Resources.Resources.DoctorsTimetable);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <i");

WriteLiteral(" class=\"icon-arrow-right-circle icons\"");

WriteLiteral("></i>\r\n                        </a>\r\n                    </h5>\r\n                <" +
"/div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"col-lg-3 box-one background-color-primary appear-animation\"");

WriteLiteral(" data-appear-animation=\"fadeInLeft\"");

WriteLiteral(" data-appear-animation-delay=\"0\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"feature-box feature-box-style-2 p-lg\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"feature-box-icon\"");

WriteLiteral(">\r\n                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 6992), Tuple.Create("\"", 7059)
, Tuple.Create(Tuple.Create("", 6998), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/img/demos/medical/icons/medical-icon-heart.png")
, 6998), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" class=\"img-responsive pt-xs\"");

WriteLiteral(" />\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"feature-box-info ml-md\"");

WriteLiteral(">\r\n                            <h4");

WriteLiteral(" class=\"m-none\"");

WriteLiteral(">");

            
            #line 111 "..\..\Views\Home\Index.cshtml"
                                          Write(Resources.Resources.MedicalTreatment);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                        </div>\r\n                    </div>\r\n              " +
"  </div>\r\n");

            
            #line 115 "..\..\Views\Home\Index.cshtml"

            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"col-lg-3 box-one background-color-primary appear-animation\"");

WriteLiteral(" data-appear-animation=\"fadeInLeft\"");

WriteLiteral(" data-appear-animation-delay=\"0\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"feature-box feature-box-style-2 p-lg\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"feature-box-icon\"");

WriteLiteral(">\r\n                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 7737), Tuple.Create("\"", 7804)
, Tuple.Create(Tuple.Create("", 7743), Tuple.Create<System.Object, System.Int32>(Href("~/assets/porto/img/demos/medical/icons/medical-icon-heart.png")
, 7743), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" class=\"img-responsive pt-xs\"");

WriteLiteral(" />\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"feature-box-info ml-md\"");

WriteLiteral(">\r\n                            <h4");

WriteLiteral(" class=\"m-none\"");

WriteLiteral(">");

            
            #line 125 "..\..\Views\Home\Index.cshtml"
                                          Write(Resources.Resources.MedicalTreatment);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                        </div>\r\n                    </div>\r\n              " +
"  </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"col-lg-3 box-two background-color-tertiary appear-animation\"");

WriteLiteral(" data-appear-animation=\"fadeInLeft\"");

WriteLiteral(" data-appear-animation-delay=\"600\"");

WriteLiteral(">\r\n                    <h5");

WriteLiteral(" class=\"m-none\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"demo-medical-doctors.html\"");

WriteLiteral(" title=\"\"");

WriteLiteral(">\r\n                            Doctors Timetable\r\n                            <i");

WriteLiteral(" class=\"icon-arrow-right-circle icons\"");

WriteLiteral("></i>\r\n                        </a>\r\n                    </h5>\r\n                <" +
"/div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"col-lg-3 box-three background-color-primary appear-animation\"");

WriteLiteral(" data-appear-animation=\"fadeInLeft\"");

WriteLiteral(" data-appear-animation-delay=\"1200\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"expanded-info p-xlg background-color-primary\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 141 "..\..\Views\Home\Index.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 141 "..\..\Views\Home\Index.cshtml"
                                 foreach (var item in openingHours)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <div");

WriteLiteral(" class=\"info custom-info log-in-info\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(" class=\"bold\"");

WriteLiteral(">");

            
            #line 144 "..\..\Views\Home\Index.cshtml"
                                                                         Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                        <div");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">");

            
            #line 145 "..\..\Views\Home\Index.cshtml"
                                                            Write(item.Subtitle);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                    </div>\r\n");

            
            #line 147 "..\..\Views\Home\Index.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </div>\r\n                        </div>\r\n             " +
"       </div>\r\n                    <h5");

WriteLiteral(" class=\"m-none\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 152 "..\..\Views\Home\Index.cshtml"
                   Write(Resources.Resources.OpeningHours);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <i");

WriteLiteral(" class=\"icon-arrow-right-circle icons\"");

WriteLiteral("></i>\r\n                    </h5>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"col-lg-3 box-four background-color-secondary p-none appear-animation\"");

WriteLiteral(" data-appear-animation=\"fadeInLeft\"");

WriteLiteral(" data-appear-animation-delay=\"1800\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"tel:+008001234567\"");

WriteLiteral(" class=\"text-decoration-none\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"feature-box feature-box-style-2 m-none\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"feature-box-icon\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"icon-call-out icons\"");

WriteLiteral("></i>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"feature-box-info ml-md\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"font-weight-light\"");

WriteLiteral(">");

            
            #line 163 "..\..\Views\Home\Index.cshtml"
                                                            Write(Resources.Resources.EmergencyCase);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                <strong");

WriteLiteral(" class=\"font-weight-normal\"");

WriteLiteral(">");

            
            #line 164 "..\..\Views\Home\Index.cshtml"
                                                               Write(OrganizationData.Organization?.Telephone);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                            </div>\r\n                        </div>\r\n  " +
"                  </a>\r\n                </div>\r\n");

            
            #line 169 "..\..\Views\Home\Index.cshtml"

            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n");

            
            #line 172 "..\..\Views\Home\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 172 "..\..\Views\Home\Index.cshtml"
         foreach (var item in shortcutContents)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"row mt-xlg pt-xlg mb-xlg pb-xs\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-8 col-md-8\"");

WriteLiteral(">\r\n                    <h2");

WriteLiteral(" class=\"font-weight-semibold mb-xs\"");

WriteLiteral(">");

            
            #line 176 "..\..\Views\Home\Index.cshtml"
                                                      Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                    <p");

WriteLiteral(" class=\"lead font-weight-normal\"");

WriteLiteral(">");

            
            #line 177 "..\..\Views\Home\Index.cshtml"
                                                  Write(item.Subtitle);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n                    <p>");

            
            #line 179 "..\..\Views\Home\Index.cshtml"
                  Write(item.MainContent.StripHtml().Chop(300).Trim());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n                    <a");

WriteLiteral(" class=\"btn btn-borders btn-quaternary custom-button text-uppercase mt-lg mb-lg f" +
"ont-weight-bold\"");

WriteAttribute("href", Tuple.Create(" href=\"", 11145), Tuple.Create("\"", 11212)
            
            #line 181 "..\..\Views\Home\Index.cshtml"
                                             , Tuple.Create(Tuple.Create("", 11152), Tuple.Create<System.Object, System.Int32>(Url.Action("Content", "Pages" , new { slug=@item.UrlSlug })
            
            #line default
            #line hidden
, 11152), false)
);

WriteLiteral(">read more</a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-4 col-md-4\"");

WriteLiteral(">\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 11326), Tuple.Create("\"", 11347)
            
            #line 184 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 11332), Tuple.Create<System.Object, System.Int32>(item.ImagePath
            
            #line default
            #line hidden
, 11332), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 11348), Tuple.Create("\"", 11369)
            
            #line 184 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 11354), Tuple.Create<System.Object, System.Int32>(item.ImageName
            
            #line default
            #line hidden
, 11354), false)
);

WriteLiteral(" class=\"img-responsive boxshadow\"");

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n");

            
            #line 187 "..\..\Views\Home\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</section>\r\n<section");

WriteLiteral(" class=\"section section-no-border\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row pt-xl\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <h2");

WriteLiteral(" class=\"font-weight-semibold mb-xs\"");

WriteLiteral(">");

            
            #line 195 "..\..\Views\Home\Index.cshtml"
                                                  Write(Resources.Resources.Departments);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                ");

WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

            
            #line 199 "..\..\Views\Home\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 199 "..\..\Views\Home\Index.cshtml"
          var i = 0;
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 200 "..\..\Views\Home\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 200 "..\..\Views\Home\Index.cshtml"
         foreach (var item in IdentityDb.IdentityDepartmentTerms.Where(d => d.Department.TenantId.Trim().Equals(Tenant.TenantId) && d.HomeVisible && d.Visible && d.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name)).OrderBy(d => d.Department.Ordinal))
        {
            if (i % 3 == 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("<div class=\"row mt-lg\">\r\n");

            
            #line 205 "..\..\Views\Home\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"feature-box feature-box-style-2 mb-xl appear-animation\"");

WriteLiteral(" data-appear-animation=\"fadeInUp\"");

WriteLiteral(" data-appear-animation-delay=\"300\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"feature-box-icon\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 12578), Tuple.Create("\"", 12598)
            
            #line 209 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 12584), Tuple.Create<System.Object, System.Int32>(item.IconPath
            
            #line default
            #line hidden
, 12584), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 12599), Tuple.Create("\"", 12622)
            
            #line 209 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 12605), Tuple.Create<System.Object, System.Int32>(item.Description
            
            #line default
            #line hidden
, 12605), false)
);

WriteLiteral(" class=\"img-responsive\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"feature-box-info ml-md\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\"font-weight-semibold\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 12796), Tuple.Create("\"", 12878)
            
            #line 212 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 12803), Tuple.Create<System.Object, System.Int32>(string.Concat(item.AbsolutePath, string.Concat("#", item.Department.Code))
            
            #line default
            #line hidden
, 12803), false)
);

WriteLiteral(" class=\"text-decoration-none\"");

WriteLiteral(">");

            
            #line 212 "..\..\Views\Home\Index.cshtml"
                                                                                                                                                                       Write(item.Value);

            
            #line default
            #line hidden
WriteLiteral("</a></h4>\r\n                        <p>");

            
            #line 213 "..\..\Views\Home\Index.cshtml"
                      Write(item.Summary);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n");

            
            #line 217 "..\..\Views\Home\Index.cshtml"
            i++;
            if (i % 3 == 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("</div>\r\n");

            
            #line 221 "..\..\Views\Home\Index.cshtml"
            }
        }

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row mt-lg pb-xlg\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 center\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"btn btn-borders btn-quaternary custom-button text-uppercase mt-lg font-we" +
"ight-bold\"");

WriteAttribute("href", Tuple.Create(" href=\"", 13356), Tuple.Create("\"", 13391)
            
            #line 225 "..\..\Views\Home\Index.cshtml"
                                   , Tuple.Create(Tuple.Create("", 13363), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Staff")
            
            #line default
            #line hidden
, 13363), false)
);

WriteLiteral(">");

            
            #line 225 "..\..\Views\Home\Index.cshtml"
                                                                                                                                             Write(Resources.Resources.ViewMore);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</section>\r\n<section");

WriteLiteral(" class=\"team\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row mt-xlg\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <h2");

WriteLiteral(" class=\"font-weight-semibold m-none\"");

WriteLiteral(">");

            
            #line 234 "..\..\Views\Home\Index.cshtml"
                                                   Write(Resources.Resources.Doctors);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                <p");

WriteLiteral(" class=\"lead font-weight-normal\"");

WriteLiteral(">");

            
            #line 235 "..\..\Views\Home\Index.cshtml"
                                              Write(Resources.Resources.OurSpecialists);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n                <div");

WriteLiteral(" id=\"porfolioAjaxBoxMedical\"");

WriteLiteral(" class=\"ajax-box ajax-box-init mb-lg\"");

WriteLiteral(">\r\n\r\n                    <div");

WriteLiteral(" class=\"bounce-loader\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"bounce1\"");

WriteLiteral("></div>\r\n                        <div");

WriteLiteral(" class=\"bounce2\"");

WriteLiteral("></div>\r\n                        <div");

WriteLiteral(" class=\"bounce3\"");

WriteLiteral("></div>\r\n                    </div>\r\n\r\n                    <div");

WriteLiteral(" class=\"ajax-box-content\"");

WriteLiteral(" id=\"porfolioAjaxBoxContentMedical\"");

WriteLiteral("></div>\r\n\r\n                </div>\r\n\r\n            </div>\r\n        </div>\r\n        " +
"<div");

WriteLiteral(" class=\"row mb-xlg\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"owl-carousel owl-theme nav-bottom rounded-nav pl-xs pr-xs\"");

WriteLiteral(" data-plugin-options=\"{\'items\': 4, \'loop\': false, \'dots\': false, \'nav\': true}\"");

WriteLiteral(">\r\n");

            
            #line 253 "..\..\Views\Home\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 253 "..\..\Views\Home\Index.cshtml"
                 foreach (var item in Model.DepartmentTerms.OrderBy(d => d.Ordinal))
                {
                    foreach (var empInDept in item.Department.EmpInDepts.OrderBy(d => d.Ordinal))
                    {
                        string personalTitle = empInDept.Employee.PersonalTitle.PersonalTitleTerms.Where(p => p.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name)).FirstOrDefault()?.Value ?? empInDept.Employee.PersonalTitle.Code;
                        var employee = IdentityDb.Employees.Where(e => e.Language.CultureName.Equals(Thread.CurrentThread.CurrentCulture.Name) && e.TranslationId == empInDept.Employee.TranslationId).FirstOrDefault();

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"pr-sm pl-sm\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 15262), Tuple.Create("\"", 15353)
            
            #line 260 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 15269), Tuple.Create<System.Object, System.Int32>(Url.Action("MemberProfile", "Staff", new { id = empInDept.Employee.TranslationId })
            
            #line default
            #line hidden
, 15269), false)
);

WriteLiteral(" data-ajax-on-page");

WriteLiteral(" class=\"text-decoration-none\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"thumb-info thumb-info-no-zoom thumb-info-hide-wrapper-bg\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"thumb-info-wrapper m-none\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("alt", Tuple.Create(" alt=\"", 15631), Tuple.Create("\"", 15674)
            
            #line 263 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 15637), Tuple.Create<System.Object, System.Int32>(empInDept.Employee.PersonalPhotoName
            
            #line default
            #line hidden
, 15637), false)
);

WriteAttribute("src", Tuple.Create(" src=\"", 15675), Tuple.Create("\"", 15823)
            
            #line 263 "..\..\Views\Home\Index.cshtml"
              , Tuple.Create(Tuple.Create("", 15681), Tuple.Create<System.Object, System.Int32>(!File.Exists(Server.MapPath(employee.PersonalPhotoPath)) ? "/assets/admin/plugins/images/users/user-icon.png" : @employee.PersonalPhotoPath
            
            #line default
            #line hidden
, 15681), false)
);

WriteLiteral(">\r\n                                    </span>\r\n                                 " +
"   <span");

WriteLiteral(" class=\"thumb-info-caption p-md pt-xlg pb-xlg\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"custom-thumb-info-title\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"custom-thumb-info-type font-weight-light text-md\"");

WriteLiteral(">");

            
            #line 267 "..\..\Views\Home\Index.cshtml"
                                                                                                      Write(empInDept.Department.DepartmentTerms.Where(d => d.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name)).FirstOrDefault().Value);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                            <span");

WriteLiteral(" class=\"custom-thumb-info-inner font-weight-semibold text-lg\"");

WriteLiteral(">");

            
            #line 268 "..\..\Views\Home\Index.cshtml"
                                                                                                          Write(personalTitle);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 268 "..\..\Views\Home\Index.cshtml"
                                                                                                                         Write(employee.FullName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                            ");

WriteLiteral("\r\n                                        </span>\r\n                              " +
"      </span>\r\n                                </span>\r\n                        " +
"    </a>\r\n                        </div>\r\n");

            
            #line 275 "..\..\Views\Home\Index.cshtml"
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</section>\r\n<section");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row mt-md\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <h2");

WriteLiteral(" class=\"font-weight-semibold m-none\"");

WriteLiteral(">");

            
            #line 285 "..\..\Views\Home\Index.cshtml"
                                                   Write(resourcesList.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                <p");

WriteLiteral(" class=\"lead font-weight-normal\"");

WriteLiteral(">");

            
            #line 286 "..\..\Views\Home\Index.cshtml"
                                              Write(resourcesList.Subtitle);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 290 "..\..\Views\Home\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 290 "..\..\Views\Home\Index.cshtml"
             foreach (var item in resourcesList.ListItems)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"col-sm-4 col-md-4\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 17388), Tuple.Create("\"", 17404)
            
            #line 293 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 17395), Tuple.Create<System.Object, System.Int32>(item.Url
            
            #line default
            #line hidden
, 17395), false)
);

WriteLiteral(" class=\"text-decoration-none\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"thumb-info thumb-info-side-image thumb-info-side-image-custom thumb-info-" +
"no-zoom thumb-info-no-zoom thumb-info-side-image-custom-highlight\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"thumb-info-side-image-wrapper\"");

WriteLiteral(">\r\n                                <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" class=\"img-responsive\"");

WriteAttribute("src", Tuple.Create(" src=\"", 17756), Tuple.Create("\"", 17777)
            
            #line 296 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 17762), Tuple.Create<System.Object, System.Int32>(item.ThumbPath
            
            #line default
            #line hidden
, 17762), false)
);

WriteLiteral(">\r\n                            </span>\r\n                            <span");

WriteLiteral(" class=\"thumb-info-caption\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"thumb-info-caption-text p-xl\"");

WriteLiteral(">\r\n                                    <h4");

WriteLiteral(" class=\"font-weight-semibold mb-xs\"");

WriteLiteral(">");

            
            #line 300 "..\..\Views\Home\Index.cshtml"
                                                                      Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                                    <p>");

            
            #line 301 "..\..\Views\Home\Index.cshtml"
                                  Write(item.Subtitle);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                </span>\r\n                            </span" +
">\r\n                        </span>\r\n                    </a>\r\n                </" +
"div>\r\n");

            
            #line 307 "..\..\Views\Home\Index.cshtml"

            }

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row pb-xlg\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 center\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"btn btn-borders btn-quaternary custom-button text-uppercase font-weight-b" +
"old\"");

WriteLiteral(">view more</a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</section>\r\n<sect" +
"ion>\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row mt-md\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <h2");

WriteLiteral(" class=\"font-weight-semibold m-none\"");

WriteLiteral(">");

            
            #line 336 "..\..\Views\Home\Index.cshtml"
                                                   Write(insuranceList.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                <p");

WriteLiteral(" class=\"lead font-weight-normal\"");

WriteLiteral(">");

            
            #line 337 "..\..\Views\Home\Index.cshtml"
                                              Write(insuranceList.Subtitle);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n        </div>\r\n            <div");

WriteLiteral(" class=\"row center\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"owl-carousel owl-theme\"");

WriteLiteral(" data-plugin-options=\"{\'items\': 6, \'autoplay\': true, \'autoplayTimeout\': 3000}\"");

WriteLiteral(">\r\n");

            
            #line 342 "..\..\Views\Home\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 342 "..\..\Views\Home\Index.cshtml"
                     foreach (var item in insuranceList.ListItems)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div>\r\n                            <img");

WriteLiteral(" class=\"img-responsive\"");

WriteAttribute("src", Tuple.Create(" src=\"", 20244), Tuple.Create("\"", 20265)
            
            #line 345 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 20250), Tuple.Create<System.Object, System.Int32>(item.ThumbPath
            
            #line default
            #line hidden
, 20250), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                            <p>");

            
            #line 346 "..\..\Views\Home\Index.cshtml"
                          Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                        </div>\r\n");

            
            #line 348 "..\..\Views\Home\Index.cshtml"
                    }    

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("\r\n                </div>\r\n            </div>\r\n    </div>\r\n</section>\r\n<section");

WriteLiteral(" class=\"section-secondary\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row mt-xlg pt-md mb-xlg pb-md\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"owl-carousel owl-theme nav-bottom rounded-nav\"");

WriteLiteral(" data-plugin-options=\"{\'items\': 1, \'loop\': false, \'dots\': false}\"");

WriteLiteral(">\r\n                <div>\r\n                    <div");

WriteLiteral(" class=\"col-md-8 col-md-offset-2 pt-xlg\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"testimonial testimonial-style-2 testimonial-with-quotes mb-none\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"testimonial-quote\"");

WriteLiteral(">“</div>\r\n                            <blockquote>\r\n                             " +
"   <p");

WriteLiteral(" class=\"font-weight-light\"");

WriteLiteral(@">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur hendrerit, leo vitae interdum pretium, tortor risus dapibus tortor, eu suscipit orci leo sed nisl. Integer et ipsum eu nulla auctor mattis sit amet in diam. Vestibulum non.</p>
                            </blockquote>
                            <div");

WriteLiteral(" class=\"testimonial-author mt-xlg\"");

WriteLiteral(">\r\n                                <p");

WriteLiteral(" class=\"text-uppercase\"");

WriteLiteral(@">
                                    <strong>John Smith</strong>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div>
                    <div");

WriteLiteral(" class=\"col-md-8 col-md-offset-2 pt-xlg\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"testimonial testimonial-style-2 testimonial-with-quotes mb-none\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"testimonial-quote\"");

WriteLiteral(">“</div>\r\n                            <blockquote>\r\n                             " +
"   <p");

WriteLiteral(" class=\"font-weight-light\"");

WriteLiteral(@">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur hendrerit, leo vitae interdum pretium, tortor risus dapibus tortor, eu suscipit orci leo sed nisl. Integer et ipsum eu nulla auctor mattis sit amet in diam. Vestibulum non.</p>
                            </blockquote>
                            <div");

WriteLiteral(" class=\"testimonial-author mt-xlg\"");

WriteLiteral(">\r\n                                <p");

WriteLiteral(" class=\"text-uppercase\"");

WriteLiteral(@">
                                    <strong>John Smith</strong>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
");

        }
    }
}
#pragma warning restore 1591
