#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cutecms_porto;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/RMS/Views/Submissions/Index.cshtml")]
    public partial class _Areas_RMS_Views_Submissions_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<cutecms_porto.Areas.RMS.Models.SubmissionViewModel>>
    {
        public _Areas_RMS_Views_Submissions_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
  
    ViewBag.MainTitle = Resources.Resources.Submissions;
    ViewBag.Title = Resources.Resources.Index;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div>");

            
            #line 6 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
Write(Html.ActionLink(Resources.Resources.DownloadApplications, "ExportApplicants", null, new { @class = "btn btn-danger" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n    <link");

WriteLiteral(" href=\"https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"https://cdn.datatables.net/buttons/1.2.1/css/buttons.dataTables.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

});

WriteLiteral("<div");

WriteLiteral(" style=\"margin-top:25px;\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" id=\"submissionsTable\"");

WriteLiteral(" class=\"table table-bordered table-hover nowrap\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th>");

            
            #line 15 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.Id));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                <th>");

            
            #line 16 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.ApplicantFullName));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                <th>");

            
            #line 17 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.SubmissionDate));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                <th");

WriteLiteral(" class=\"select-filter\"");

WriteLiteral(">");

            
            #line 18 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                                     Write(Html.DisplayNameFor(model => model.VacancyTitle));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                <th");

WriteLiteral(" class=\"select-filter\"");

WriteLiteral(">");

            
            #line 19 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                                     Write(Html.DisplayNameFor(model => model.Department));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                <th>");

            
            #line 20 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
               Write(Resources.Resources.Actions);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n            </tr>\r\n        </thead>\r\n        <tfoot>\r\n            <tr>\r\n  " +
"              <th></th>\r\n                <th></th>\r\n                <th></th>\r\n " +
"               <th>");

            
            #line 28 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.VacancyTitle));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                <th>");

            
            #line 29 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.Department));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                <th></th>\r\n            </tr>\r\n        </tfoot>\r\n    </tabl" +
"e>\r\n</div>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap4.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"//cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"//cdn.datatables.net/buttons/1.2.1/js/buttons.html5.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"https://cdn.datatables.net/buttons/1.2.1/js/dataTables.buttons.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"//cdn.datatables.net/buttons/1.2.1/js/buttons.colVis.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"//cdn.datatables.net/buttons/1.2.1/js/buttons.print.min.js\"");

WriteLiteral(@"></script>
    <script>
        $('.tfoot_search').each(function () {
            var title = $('.datatable-column-search-inputs thead th').eq($(this).index()).text();
            $(this).html('<input type=""text"" class=""form-control input-sm"" placeholder=""Search ' + title + '"" />');
        });
        $(document).ready(function () {
            var oTable = $('#submissionsTable').DataTable({
                ""serverSide"": true,
                ""autoWidth"": false,
                ""scrollX"": true,
                ""lengthMenu"": [[10, 25, 50, -1], [10, 25, 50, ""All""]],
                dom: 'lBfrtip',
                buttons: [
             {
                 text: '");

            
            #line 59 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                   Write(Resources.Resources.Reload);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                 action: function (e, dt, node, config) {\r\n                  " +
"   dt.ajax.reload();\r\n                 }\r\n             },\r\n             {\r\n     " +
"            text: \'");

            
            #line 65 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                   Write(Resources.Resources.Copy);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                 extend: \'copyHtml5\',\r\n                 exportOptions: {\r\n   " +
"                  columns: \':visible\'\r\n                 }\r\n             },\r\n    " +
"        {\r\n                text: \'");

            
            #line 72 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                  Write(Resources.Resources.ExportExcel);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                extend: \'excelHtml5\',\r\n                exportOptions: {\r\n    " +
"                columns: \':visible\'\r\n                }\r\n            },\r\n        " +
"    {\r\n                text: \'");

            
            #line 79 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                  Write(Resources.Resources.ExportPDF);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                extend: \'pdfHtml5\',\r\n                exportOptions: {\r\n      " +
"              columns: \':visible\'\r\n                }\r\n            },\r\n          " +
"  {\r\n                text: \'");

            
            #line 86 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                  Write(Resources.Resources.Print);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                extend: \'print\',\r\n                exportOptions: {\r\n         " +
"           columns: \':visible\'\r\n                }\r\n            },\r\n            {" +
"\r\n                text: \'");

            
            #line 93 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                  Write(Resources.Resources.ColVis);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                extend: \'colvis\',\r\n            },\r\n                ],\r\n      " +
"          //\"responsive\": true,\r\n                \"language\": {\r\n                " +
"    \"url\": \"");

            
            #line 99 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                       Write(Resources.Resources.DataTableLanguage);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                },\r\n                \"ajax\": {\r\n                    \"type\": \"PO" +
"ST\",\r\n                    \"url\": \"");

            
            #line 103 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                       Write(Url.Action("DataHandler", "Submissions", new {id=ViewBag.VacancyId, area = "RMS" }));

            
            #line default
            #line hidden
WriteLiteral(@""",
                    ""contentType"": 'application/json; charset=utf-8',
                    'data': function (data) {
                        return data = JSON.stringify(data);
                    }
                },
                ""processing"": true,
                ""paging"": true,
                ""deferRender"": true,
                ""columns"": [
               { ""data"": ""Id"" },
               { ""data"": ""ApplicantFullName"" },
               { ""data"": ""SubmissionDate"" },
               { ""data"": ""VacancyTitle"" },
               { ""data"": ""Department"", ""visible"": false },
               {
                   ""data"": ""Action"",
                   ""sortable"": false,
                   ""render"": function (data, type, col) {
                       return '<a class=\'btn\' href=\'' + '");

            
            #line 122 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                                                       Write(Url.Action("Details", "Submissions"));

            
            #line default
            #line hidden
WriteLiteral("?id=\' + col[\"Id\"] + \'\\\'>");

            
            #line 122 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                                                                                                                    Write(Resources.Resources.View);

            
            #line default
            #line hidden
WriteLiteral("</a>\'\r\n                       + \'|<a class=\\\'btn\\\' href=\\\'\' + \'");

            
            #line 123 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                                                   Write(Url.Action("ExportCV", "Submissions"));

            
            #line default
            #line hidden
WriteLiteral("?id=\' + col[\"Id\"] + \'\\\'>");

            
            #line 123 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                                                                                                                 Write(Resources.Resources.CurriculumVitae);

            
            #line default
            #line hidden
WriteLiteral("</a>\'\r\n                       + \'|<a class=\\\'btn\\\' href=\\\'\' + \'");

            
            #line 124 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                                                   Write(Url.Action("ExportApplicant", "Submissions"));

            
            #line default
            #line hidden
WriteLiteral("?id=\' + col[\"Id\"] + \'\\\'>");

            
            #line 124 "..\..\Areas\RMS\Views\Submissions\Index.cshtml"
                                                                                                                        Write(Resources.Resources.Export);

            
            #line default
            #line hidden
WriteLiteral("</a>\';\r\n                       ");

WriteLiteral(@"
                   }
                   //""render"": function (o) { return '<i class=""ui-tooltip fa fa-pencil"" style=""font-size: 22px;"" data-original-title=""Edit""></i><i class=""ui-tooltip fa fa-trash-o"" style=""font-size: 22px;"" data-original-title=""Delete""></i>'; }
               },
                ],
                ""order"": [0, ""asc""],
                ""initComplete"": function () {
                    this.api().columns('.select-filter').every(function () {
                        var column = this;
                        var select = $('<select><option value=""""></option></select>')
                                   .appendTo($(column.footer()).empty())
                                   .on('change', function () {
                                       var val = $(this).val();
                                       column
                                           .search(val, true, false)
                                           .draw();
                                   });
                        column.data().unique().sort().each(function (d, j) {
                            select.append('<option value=""' + d + '"">' + d + '</option>')
                        });
                    });
                }
            });
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
