//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cutecms_porto.Areas.CMS.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class MenuItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuItem()
        {
            this.Contents = new HashSet<Content>();
            this.MenuItems1 = new HashSet<MenuItem>();
        }

        public int Id { get; set; }
        [Required(ErrorMessageResourceType = typeof(App_GlobalResources.ValidationResources), ErrorMessageResourceName = "PropertyValueRequired")]
        [Display(Name = "Name", ResourceType = typeof(Resources.Resources))]
        public string Name { get; set; }
        [Display(Name = "Path", ResourceType = typeof(Resources.Resources))]
        public string Path { get; set; }
        [Required(ErrorMessageResourceType = typeof(App_GlobalResources.ValidationResources), ErrorMessageResourceName = "PropertyValueRequired")]
        [Display(Name = "Menu", ResourceType = typeof(Resources.Resources))]
        public int MenuId { get; set; }
        [Display(Name = "Parent", ResourceType = typeof(Resources.Resources))]
        public Nullable<int> ParentId { get; set; }
        [Display(Name = "CssClass", ResourceType = typeof(Resources.Resources))]
        public string CssClass { get; set; }
        [Required(ErrorMessageResourceType = typeof(App_GlobalResources.ValidationResources), ErrorMessageResourceName = "PropertyValueRequired")]
        [Display(Name = "Ordinal", ResourceType = typeof(Resources.Resources))]
        public int Ordinal { get; set; }
        [Display(Name = "IsCms", ResourceType = typeof(Resources.Resources))]
        public bool IsCms { get; set; }
        [Display(Name = "IsParent", ResourceType = typeof(Resources.Resources))]
        public bool IsParent { get; set; }
        [Display(Name = "IsLeaf", ResourceType = typeof(Resources.Resources))]
        public bool IsLeaf { get; set; }
        [Display(Name = "Visible", ResourceType = typeof(Resources.Resources))]
        public bool Visible { get; set; }
        [Required(ErrorMessageResourceType = typeof(App_GlobalResources.ValidationResources), ErrorMessageResourceName = "PropertyValueRequired")]
        [Display(Name = "Language", ResourceType = typeof(Resources.Resources))]
        public int LanguageId { get; set; }
        [Required(ErrorMessageResourceType = typeof(App_GlobalResources.ValidationResources), ErrorMessageResourceName = "PropertyValueRequired")]
        [Display(Name = "Status", ResourceType = typeof(Resources.Resources))]
        public int StatusId { get; set; }
        [Display(Name = "Content", ResourceType = typeof(Resources.Resources))]
        public Nullable<int> ContentId { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Contents { get; set; }
        public virtual CMSLanguage Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItem> MenuItems1 { get; set; }
        public virtual MenuItem MenuItem1 { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual CMSStatus Status { get; set; }
    }
}
