#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 3 "..\..\Views\Staff\Index.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cutecms_porto;
    
    #line 2 "..\..\Views\Staff\Index.cshtml"
    using cutecms_porto.Areas.Identity.Models.DBModel;
    
    #line default
    #line hidden
    using cutecms_porto.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Staff/Index.cshtml")]
    public partial class _Views_Staff_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<IdentityDepartment>>
    {

#line 140 "..\..\Views\Staff\Index.cshtml"
public System.Web.WebPages.HelperResult GetTreeView(IEnumerable<IdentityDepartment> departments, int? parentId)
                                    {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 141 "..\..\Views\Staff\Index.cshtml"
                                     
IdentityEntities db = new IdentityEntities();
var departmentLists = departments.Where(d => d.ParentId.Equals(parentId) && d.DepartmentTerms.Count != 0).OrderBy(d => d.Ordinal);
foreach (var item in departmentLists.Where(d => d.DepartmentTerms.Any(dl => dl.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name))))
{


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <li>\r\n");


#line 147 "..\..\Views\Staff\Index.cshtml"
            

#line default
#line hidden

#line 147 "..\..\Views\Staff\Index.cshtml"
              
                var submenu = departmentLists.Where(a => a.ParentId.Equals(parentId)).Count();
            

#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n            <span><i");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-folder-open\"");

WriteLiteralTo(__razor_helper_writer, "></i>");


#line 150 "..\..\Views\Staff\Index.cshtml"
                                   WriteTo(__razor_helper_writer, item.DepartmentTerms.Where(d => d.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name)).FirstOrDefault().Value);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</span>\r\n            <a");

WriteLiteralTo(__razor_helper_writer, " class=\"fa fa-users fa-1x\"");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 6133), Tuple.Create("\"", 6196)

#line 151 "..\..\Views\Staff\Index.cshtml"
, Tuple.Create(Tuple.Create("", 6140), Tuple.Create<System.Object, System.Int32>(Url.Action("EmpsInDept", "Staff", new { id = item.Id })

#line default
#line hidden
, 6140), false)
);

WriteLiteralTo(__razor_helper_writer, "></a>\r\n");


#line 152 "..\..\Views\Staff\Index.cshtml"
            

#line default
#line hidden

#line 152 "..\..\Views\Staff\Index.cshtml"
             if (item.EmpInDepts != null)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <ul>\r\n");


#line 155 "..\..\Views\Staff\Index.cshtml"
                    

#line default
#line hidden

#line 155 "..\..\Views\Staff\Index.cshtml"
                      var manager = db.Employees.Where(e => e.Language.CultureName.Equals(Thread.CurrentThread.CurrentCulture.Name) && e.TranslationId == item.ManagerId).FirstOrDefault(); 

#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "             \r\n");


#line 156 "..\..\Views\Staff\Index.cshtml"
                    

#line default
#line hidden

#line 156 "..\..\Views\Staff\Index.cshtml"
                     if (manager != null)
                    {
                        string personalTitle = item.Employee.PersonalTitle.PersonalTitleTerms.Where(p => p.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name)).FirstOrDefault()?.Value ?? item.Employee.PersonalTitle.Code;


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                        <li><span");

WriteLiteralTo(__razor_helper_writer, " class=\"wheat-color\"");

WriteLiteralTo(__razor_helper_writer, "><i");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-user\"");

WriteLiteralTo(__razor_helper_writer, "></i><a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 6897), Tuple.Create("\"", 6977)

#line 159 "..\..\Views\Staff\Index.cshtml"
                       , Tuple.Create(Tuple.Create("", 6904), Tuple.Create<System.Object, System.Int32>(Url.Action("MemberProfile", "Staff", new { id = manager.TranslationId })

#line default
#line hidden
, 6904), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 159 "..\..\Views\Staff\Index.cshtml"
                                                                                                                                                    WriteTo(__razor_helper_writer, personalTitle);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " ");


#line 159 "..\..\Views\Staff\Index.cshtml"
                                                                                                                                                                   WriteTo(__razor_helper_writer, manager.FullName);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a></span></li>\r\n");


#line 160 "..\..\Views\Staff\Index.cshtml"
                    }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                    ");


#line 161 "..\..\Views\Staff\Index.cshtml"
                     foreach (var empInDept in item.EmpInDepts.Where(e => e.EmpId != e.Department.ManagerId).OrderBy(ed => ed.Employee.Ordinal))
                    {
                        string personalTitle = empInDept.Employee.PersonalTitle.PersonalTitleTerms.Where(p => p.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name)).FirstOrDefault()?.Value ?? empInDept.Employee.PersonalTitle.Code;
                        var employee = db.Employees.Where(e => e.TranslationId == empInDept.Employee.TranslationId && e.Language.CultureName.Trim().Equals(Thread.CurrentThread.CurrentCulture.Name)).FirstOrDefault();
                        if (employee != null)
                        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                            <li><span><i");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-user\"");

WriteLiteralTo(__razor_helper_writer, "></i><a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 7849), Tuple.Create("\"", 7940)

#line 167 "..\..\Views\Staff\Index.cshtml"
       , Tuple.Create(Tuple.Create("", 7856), Tuple.Create<System.Object, System.Int32>(Url.Action("MemberProfile", "Staff", new { id = empInDept.Employee.TranslationId })

#line default
#line hidden
, 7856), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 167 "..\..\Views\Staff\Index.cshtml"
                                                                                                                                               WriteTo(__razor_helper_writer, personalTitle);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " ");


#line 167 "..\..\Views\Staff\Index.cshtml"
                                                                                                                                                              WriteTo(__razor_helper_writer, employee.FullName);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a></span></li>\r\n");


#line 168 "..\..\Views\Staff\Index.cshtml"
                        }
                    }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                </ul>\r\n");


#line 171 "..\..\Views\Staff\Index.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            ");


#line 172 "..\..\Views\Staff\Index.cshtml"
             if (submenu > 0)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <ul>\r\n");

WriteLiteralTo(__razor_helper_writer, "                    ");


#line 175 "..\..\Views\Staff\Index.cshtml"
WriteTo(__razor_helper_writer, GetTreeView(departments, item.Id));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n                    ");

WriteLiteralTo(__razor_helper_writer, "\r\n                </ul>\r\n");


#line 178 "..\..\Views\Staff\Index.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        </li>\r\n");


#line 180 "..\..\Views\Staff\Index.cshtml"
                }


#line default
#line hidden
});

#line 181 "..\..\Views\Staff\Index.cshtml"
}
#line default
#line hidden

        public _Views_Staff_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Staff\Index.cshtml"
  
    ViewBag.Title = Resources.Resources.MedicalStaff;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Styles", () => {

WriteLiteral("\r\n    <style>\r\n        .glyphicon-folder-open {\r\n            margin-right: 10px !" +
"important;\r\n        }\r\n        .glyphicon-folder-close {\r\n            margin-rig" +
"ht: 10px !important;\r\n        }\r\n        .glyphicon-user {\r\n            margin-r" +
"ight: 10px !important;\r\n        }\r\n        .dir {\r\n            direction: ltr !i" +
"mportant;\r\n        }\r\n        .tree {\r\n            min-height: 20px;\r\n          " +
"  padding: 19px;\r\n            margin-bottom: 20px;\r\n            background-color" +
": #fbfbfb;\r\n            border: 1px solid #999;\r\n            -webkit-border-radi" +
"us: 4px;\r\n            -moz-border-radius: 4px;\r\n            border-radius: 4px;\r" +
"\n            -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);\r\n         " +
"   -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);\r\n            box-shadow" +
": inset 0 1px 1px rgba(0, 0, 0, 0.05);\r\n        }\r\n            .tree li {\r\n     " +
"           list-style-type: none;\r\n                margin: 0;\r\n                p" +
"adding: 10px 5px 0 5px;\r\n                position: relative;\r\n            }\r\n   " +
"             .tree li::before, .tree li::after {\r\n                    content: \'" +
"\';\r\n                    left: -20px;\r\n                    position: absolute;\r\n " +
"                   right: auto;\r\n                }\r\n                .tree li::be" +
"fore {\r\n                    border-left: 1px solid #999;\r\n                    bo" +
"ttom: 50px;\r\n                    height: 100%;\r\n                    top: 0;\r\n   " +
"                 width: 1px;\r\n                }\r\n                .tree li::after" +
" {\r\n                    border-top: 1px solid #999;\r\n                    height:" +
" 20px;\r\n                    top: 25px;\r\n                    width: 25px;\r\n      " +
"          }\r\n                .tree li span {\r\n                    -moz-border-ra" +
"dius: 5px;\r\n                    -webkit-border-radius: 5px;\r\n                   " +
" border: 1px solid #999;\r\n                    border-radius: 5px;\r\n             " +
"       display: inline-block;\r\n                    padding: 3px 8px;\r\n          " +
"          text-decoration: none;\r\n                }\r\n                .tree li.pa" +
"rent_li > span {\r\n                    cursor: pointer;\r\n                }\r\n     " +
"       .tree > ul > li::before, .tree > ul > li::after {\r\n                border" +
": 0;\r\n            }\r\n            .tree li:last-child::before {\r\n                " +
"height: 30px;\r\n            }\r\n            .tree li.parent_li > span:hover, .tree" +
" li.parent_li > span:hover + ul li span {\r\n                background: #eee;\r\n  " +
"              border: 1px solid #94a0b4;\r\n                color: #000;\r\n        " +
"    }\r\n        .wheat-color {\r\n            background-color: wheat;\r\n        }\r\n" +
"        /*.tree li ul > li {\r\n                display: none;\r\n            }*/\r\n " +
"   </style>\r\n");

});

DefineSection("PageHeader", () => {

WriteLiteral("\r\n    <section");

WriteLiteral(" class=\"page-header\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                    <h1>");

            
            #line 96 "..\..\Views\Staff\Index.cshtml"
                   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </section>" +
"\r\n");

});

WriteLiteral("<section>\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                <h3>");

            
            #line 106 "..\..\Views\Staff\Index.cshtml"
               Write(Resources.Resources.SearchBy);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n");

            
            #line 107 "..\..\Views\Staff\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 107 "..\..\Views\Staff\Index.cshtml"
                 using (Html.BeginForm("Search", "Staff", FormMethod.Post))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 110 "..\..\Views\Staff\Index.cshtml"
                   Write(Html.Label(Resources.Resources.EmployeeName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 111 "..\..\Views\Staff\Index.cshtml"
                   Write(Html.TextBox("EmpName", string.Empty, htmlAttributes: new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 114 "..\..\Views\Staff\Index.cshtml"
                   Write(Html.Label(Resources.Resources.EmployeeType));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 115 "..\..\Views\Staff\Index.cshtml"
                   Write(Html.DropDownList("EmpTypeId", null, string.Empty, htmlAttributes: new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

            
            #line 117 "..\..\Views\Staff\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 120 "..\..\Views\Staff\Index.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"submit\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4377), Tuple.Create("\"", 4412)
            
            #line 122 "..\..\Views\Staff\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4385), Tuple.Create<System.Object, System.Int32>(Resources.Resources.Search
            
            #line default
            #line hidden
, 4385), false)
);

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" />\r\n                    </div>\r\n");

            
            #line 124 "..\..\Views\Staff\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                <h3>");

            
            #line 127 "..\..\Views\Staff\Index.cshtml"
               Write(Resources.Resources.SearchByDepartmet);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n");

            
            #line 128 "..\..\Views\Staff\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 128 "..\..\Views\Staff\Index.cshtml"
                 using (Html.BeginForm("Index", "Departments", FormMethod.Get))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"tree well dir\"");

WriteLiteral(">\r\n");

            
            #line 134 "..\..\Views\Staff\Index.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 134 "..\..\Views\Staff\Index.cshtml"
                                     if (Model != null && Model.Count() > 0)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <ul>\r\n");

WriteLiteral("                                            ");

            
            #line 137 "..\..\Views\Staff\Index.cshtml"
                                       Write(GetTreeView(Model, null));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </ul>\r\n");

            
            #line 139 "..\..\Views\Staff\Index.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    ");

WriteLiteral("                                </div>\r\n                            </div>\r\n     " +
"                   </div>\r\n                    </div>\r\n");

            
            #line 186 "..\..\Views\Staff\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</section>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(function () {
            $('.tree li:has(ul)').addClass('parent_li').find(' > span').attr('title', 'Collapse this branch');
            $('.tree li.parent_li > span').on('click', function (e) {
                var children = $(this).parent('li.parent_li').find(' > ul > li');
                if (children.is("":visible"")) {
                    children.hide('fast');
                    $(this).attr('title', 'Expand this branch').find(' > i').addClass('glyphicon-folder-close').removeClass('glyphicon-folder-open');
                } else {
                    children.show('fast');
                    $(this).attr('title', 'Collapse this branch').find(' > i').addClass('glyphicon-folder-open').removeClass('glyphicon-folder-close');
                }
                e.stopPropagation();
            });
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
